import { defineRecipe, prependRecipeLandmark, type RecipeConfig } from "../factory";
import { DIAGNOSTIC_DECK_ASSETS } from "./assets";

const config = {
  templateId: "diagnostic-deck", templateVersion: 2,
  concept: { name: "Diagnostic Deck", rationale: "A dense exact-unit exchange where grade, inspection, and warranty evidence precede price.", noveltySignature: ["diagnostic-terminal", "exact-unit-passports", "deck-snap-comparison"] },
  designSystem: {
    displayFontId: "archivo-narrow", bodyFontId: "ibm-plex-mono",
    tokens: { paper: "#e9e8df", ink: "#141613", green: "#b4ff47", amber: "#ffb727", red: "#ff5a48", panel: "#20231f", rule: "#353831", "terminal-gap": "20px" },
    breakpoints: { compact: 850, wide: 1280 }, iconStyle: "terminal condition marks and warranty-status glyphs", motionStyle: "deck snap with evidence-panel expansion",
    globalCss: `.terminal-title{font-family:var(--font-display);font-weight:700;letter-spacing:-.055em;line-height:.86;text-transform:uppercase}.diagnostic-label{font-family:var(--font-body);letter-spacing:.12em;text-transform:uppercase}`,
  },
  archetype: { composition: "diagnostic-terminal", hero: "grade-diagnostic-hero", scroll: "deck-snap", cards: "diagnostic-cards", iconography: ["terminal condition marks", "warranty status glyphs"] },
  surfaces: {
    shell: { signature: "system-status header with command navigation and exact-unit reservation drawer", source: {
      html: `<header class="terminal-shell"><span class="niche-icon niche-icon--diagnostic" aria-hidden="true">&#9635;</span><a class="terminal-title" data-cd-route="home" data-cd-text="store.name">Diagnostic Deck</a><nav aria-label="Device exchange"><a data-cd-route="collection">Inventory</a><a data-cd-route="search">Query</a><a data-cd-route="account">Account</a><a data-cd-route="cart">Reserved <span data-cd-text="cart.count"></span></a></nav><span class="diagnostic-label">Systems operational</span></header><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="paper ink green"></aside><footer data-cd-policy-links></footer>`,
      css: `.terminal-shell nav{display:flex;gap:.75rem}.terminal-shell nav a{border:1px solid var(--rule);padding:.7rem}.terminal-title{font-size:1.6rem}.diagnostic-label{font-size:.62rem;color:var(--green)}@media(max-width:720px){.terminal-shell{display:grid;gap:.55rem}.terminal-shell nav{max-width:100%;overflow-x:auto}.terminal-shell nav a{min-width:max-content}.diagnostic-label{order:-1}}`, requiredData: [], requiredCapabilities: [],
    } },
    home: { signature: "scan-target hero joined to three diagnostic readouts and an exact-unit evidence deck", source: {
      html: `<main><section class="scan-hero"><figure><img data-cd-asset="hero" alt="Refurbished computer on a diagnostic inspection bench" width="1600" height="1200"></figure><div class="scan-copy resilient-copy"><small class="diagnostic-label">Grade diagnostic</small><h1 class="terminal-title">Known condition. Zero guesswork.</h1><p>Every exact unit carries inspection, battery, port, repair, and warranty evidence.</p><a data-cd-route="collection">Open live inventory</a></div></section><section class="readout-bank"><div class="readout-cell"><b>36-point</b><span>Bench test</span></div><div class="readout-cell"><b>Exact-unit</b><span>Photography</span></div><div class="readout-cell"><b>12-month</b><span>Warranty evidence</span></div></section><section data-cd-repeat="featured.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="520" height="680"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Open passport</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="bench-empty resilient-copy" data-cd-empty-state>0 matching records. Adjust the diagnostic query.</p></main>`,
      css: `.scan-hero{display:grid;grid-template-columns:1.15fr .85fr;min-height:72dvh;border-bottom:1px solid var(--ink)}.scan-hero figure{margin:0}.scan-hero img{display:block;width:100%;height:72dvh;object-fit:cover;filter:grayscale(.25) contrast(1.08)}.scan-copy{align-self:center;padding:clamp(2rem,5vw,5rem)}.scan-copy h1{font-size:clamp(3.25rem,5.8vw,5.25rem);overflow-wrap:normal}.readout-bank{display:grid;grid-template-columns:repeat(3,1fr);border-bottom:1px solid var(--ink);overflow-x:auto;scroll-snap-type:x mandatory}.readout-cell{padding:1.5rem;scroll-snap-align:start}.scan-copy,.bench-empty,.resilient-copy{overflow-wrap:anywhere}.bench-empty{padding:2rem}@media(max-width:850px){.scan-hero{grid-template-columns:1fr}.scan-hero img{height:46dvh}.readout-bank{grid-auto-flow:column;grid-auto-columns:80%;grid-template-columns:none}}@media(prefers-reduced-motion:reduce){.readout-bank{scroll-snap-type:none}}`, requiredData: [], requiredCapabilities: [],
    } },
    collection: { signature: "sticky diagnostic column headers over expandable exact-unit passport records", source: {
      html: `<main><header class="matrix-head resilient-copy"><small class="diagnostic-label">Bench inventory</small><h1 class="terminal-title" data-cd-text="collection.title"></h1><p data-cd-text="collection.description"></p><b data-cd-text="collection.productCount"></b></header><nav class="matrix-filters"><button value="laptop" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="category">Laptop</button><button value="grade-a" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Grade A</button><button value="title_asc" data-cd-on="click" data-cd-action="collection.sort">Battery health</button></nav><section data-cd-repeat="collection.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="320" height="240"><h2 data-cd-text="product.title"></h2><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><details class="passport-evidence"><summary>Expand evidence</summary><p data-cd-text="product.description"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Open exact unit</a></details><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="zero-records resilient-copy" data-cd-empty-state>0 matching records. Clear a grade or device filter.</p></main>`,
      css: `.matrix-head{padding:clamp(2rem,5vw,5rem);border-bottom:1px solid var(--ink)}.matrix-head h1{font-size:clamp(4rem,9vw,9rem)}.matrix-filters{position:sticky;top:0;display:flex;gap:.5rem;padding:1rem;background:var(--paper)}.matrix-filters button{padding:.7rem;border:1px solid var(--ink);background:transparent}.passport-evidence[open]{border-left:4px solid var(--green)}.matrix-head,.zero-records,.resilient-copy{overflow-wrap:anywhere}.zero-records{padding:1.5rem}`, requiredData: [], requiredCapabilities: [],
    } },
    product: { signature: "exact-unit photo evidence grid paired with condition passport and reserved-unit controls", source: {
      html: `<main><section class="evidence-gallery" data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="960" height="960"></figure></section><header class="passport-copy resilient-copy"><small class="diagnostic-label">Exact-unit passport</small><h1 class="terminal-title" data-cd-text="product.title"></h1><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><p>Sold out units preserve their diagnostic record and warranty history.</p></header><section data-cd-repeat="product.variants"><div data-cd-key="variant.id"><b data-cd-text="variant.title"></b><span data-cd-text="variant.availability"></span><strong data-cd-money="variant.price"></strong></div></section><div data-cd-slot="variantPicker" data-cd-host-size="block" data-cd-theme-tokens="paper ink green"></div><div data-cd-slot="addToCart" data-cd-host-size="block" data-cd-theme-tokens="paper ink green"></div></main>`,
      css: `.evidence-gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:var(--ink)}.evidence-gallery figure{margin:0}.evidence-gallery img{display:block;width:100%;height:65dvh;object-fit:cover}.passport-copy{padding:clamp(2rem,5vw,5rem);max-width:70rem}.passport-copy h1{font-size:clamp(4rem,8vw,8rem)}.passport-copy,.resilient-copy{overflow-wrap:anywhere}@media(max-width:850px){.evidence-gallery{grid-template-columns:1fr}.evidence-gallery img{height:50dvh}}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "product",
    } },
    search: { signature: "command-line query header feeding a dense ranked record deck and zero-result diagnostic", source: {
      html: `<main><header class="command-query resilient-copy"><small class="diagnostic-label">Query inventory</small><h1 class="terminal-title" data-cd-text="search.query">Search model or use case</h1><input aria-label="Query inventory" type="search" name="q" value="" placeholder="Model, grade, or specification" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Execute query</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear command</button></header><section data-cd-repeat="search.results"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><span data-cd-text="product.availability"></span><b data-cd-money="product.price"></b><a data-cd-route="product" data-cd-param-handle="product.handle">Open record</a></article></section><p class="query-zero resilient-copy" data-cd-empty-state>0 matching records. Query a model, grade, specification, or use case.</p></main>`,
      css: `.command-query{padding:clamp(2rem,7vw,7rem);background:var(--panel);color:var(--paper)}.command-query h1{font-size:clamp(3.5rem,8vw,8rem);color:var(--green)}.command-query input,.command-query button{padding:.75rem;margin-right:.5rem}.command-query,.query-zero,.resilient-copy{overflow-wrap:anywhere}.query-zero{padding:2rem}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "search",
    } },
    cart: { signature: "reserved exact-unit ledger with per-record quantity controls and terminal order tally", source: {
      html: `<main><header class="reserve-head resilient-copy"><small class="diagnostic-label">Reserved exact units</small><h1 class="terminal-title">Reservation deck</h1><span data-cd-text="cart.count"></span></header><section data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><span data-cd-text="cartLine.quantity"></span><b data-cd-money="cartLine.unitPrice"></b><strong data-cd-money="cartLine.total"></strong><div data-cd-slot="cartLineControls" data-cd-host-size="inline"></div></article></section><aside class="reserve-total resilient-copy"><span>Subtotal</span><b data-cd-money="cart.subtotal"></b><span>Total</span><strong data-cd-money="cart.total"></strong></aside><div data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="paper ink green"></div><p class="reserve-empty resilient-copy" data-cd-empty-state>No exact units reserved. Return to the live diagnostic matrix.</p></main>`,
      css: `.reserve-head{padding:clamp(2rem,6vw,6rem);background:var(--ink);color:var(--paper)}.reserve-head h1{font-size:clamp(4rem,8vw,8rem)}.reserve-total{display:grid;grid-template-columns:1fr auto;gap:1rem;padding:2rem;max-width:40rem;margin-left:auto}.reserve-head,.reserve-total,.reserve-empty,.resilient-copy{overflow-wrap:anywhere}.reserve-empty{padding:2rem}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "cart",
    } },
    checkout: { signature: "terminal checkout with exact-unit summary aside and inspection-warranty trust record", source: {
      html: `<header class="checkout-record"><small>Secure checkout record</small><h1 data-cd-text="store.name">Diagnostic Deck</h1><p>Exact-unit identifiers, condition records, and warranty evidence remain attached to the order.</p></header><aside class="warranty-rail"><b>Bench warranty</b><span>Encrypted payment</span><span>Tracked exact-unit dispatch</span></aside><footer data-cd-policy-links></footer>`,
      css: `.checkout-record{padding:44px;max-width:780px}.checkout-record h1{font-size:68px}.warranty-rail{display:grid;gap:10px;padding:28px;background-color:var(--panel);color:var(--paper)}`,
      layout: { columnMode: "summaryAside", sectionOrder: ["contact", "shipping", "delivery", "payment", "consent", "summary"], spacingTokenId: "terminal-gap", surfaceTokenIds: ["paper", "ink", "green", "panel"] },
    } },
  }, assets: DIAGNOSTIC_DECK_ASSETS,
} satisfies RecipeConfig<"diagnostic-deck">;

config.surfaces.shell.source.css += `.terminal-shell{display:grid;grid-template-columns:auto minmax(10rem,1fr) auto auto;align-items:center;gap:1rem;min-height:4rem;padding:.75rem 1rem;background:var(--ink);color:var(--paper);border-bottom:1px solid var(--green)}.terminal-shell a{color:var(--paper);text-decoration:none}.terminal-shell nav a:hover{background:var(--green);color:var(--ink)}.terminal-shell~footer{display:flex;flex-wrap:wrap;gap:1rem;padding:1rem;background:var(--panel);color:var(--paper)}.terminal-shell~footer a{color:var(--paper);text-decoration:none}@media(max-width:720px){.terminal-shell{grid-template-columns:1fr}.terminal-shell nav{padding-bottom:.25rem}}`;
config.surfaces.home.source.html = config.surfaces.home.source.html.replace(
  `class="readout-bank"`,
  `class="readout-bank" tabindex="0" aria-label="Diagnostic readouts"`,
);
const distinguishedConfig = {
  ...config,
  surfaces: {
    ...config.surfaces,
    product: {
      ...config.surfaces.product,
      source: prependRecipeLandmark(config.surfaces.product.source, `<nav class="passport-sections" aria-label="Device passport"><span>Unit</span><span>Condition</span><span>Warranty</span></nav>`),
    },
    cart: {
      ...config.surfaces.cart,
      source: prependRecipeLandmark(config.surfaces.cart.source, `<aside class="reservation-status"><small>Exact units held for checkout</small></aside>`),
    },
  },
};

export const DIAGNOSTIC_DECK_RECIPE = defineRecipe(distinguishedConfig);
export const DIAGNOSTIC_DECK_BUNDLE = DIAGNOSTIC_DECK_RECIPE.bundle;
