// app/styles/__tests__/storefront-css.test.ts
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const css = readFileSync(fileURLToPath(new URL("../storefront.css", import.meta.url)), "utf8");

describe("storefront.css", () => {
  it("ships the base class vocabulary the routes render", () => {
    for (const sel of [".cd-store", ".cd-store__grid", ".cd-product-card", ".cd-pdp__buy"]) {
      expect(css).toContain(sel);
    }
  });

  it("styles the image hero: full-bleed background image with a readable overlay", () => {
    expect(css).toContain(".cd-hero__bg"); // the background <img>
    expect(css).toContain(".cd-block--hero[data-has-image]"); // the overlay/scrim treatment
  });

  it("carries no AI/provenance markers (browser-source hygiene)", () => {
    expect(css.toLowerCase()).not.toMatch(/claude|chatgpt|copilot|vibecod|generated by|ported from|ponytail/);
  });
});
