import { defineRecipe, prependRecipeLandmark, wrapRecipeComposition, type RecipeConfig } from "../factory";
import { DAILY_PROTOCOL_ASSETS } from "./assets";

const shell = {
  html: `<header class="protocol-shell"><span class="niche-icon niche-icon--protocol" aria-hidden="true">&#9201;</span><a class="protocol-brand" data-cd-route="home"><span data-cd-text="store.name"></span><b>Daily / Protocol</b></a><nav class="protocol-nav"><a data-cd-route="collection">Protocol</a><a data-cd-route="search">Evidence search</a><a data-cd-route="account">My routine</a><a data-cd-route="cart">Stack <span data-cd-text="cart.count"></span></a></nav><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="ink cobalt paper"></aside></header><footer class="protocol-footer"><span data-cd-text="store.name"></span><nav data-cd-policy-links></nav></footer>`,
  css: `.protocol-brand { color:var(--ink); font-family:var(--font-display); font-size:1.3rem; font-weight:700; text-decoration:none } .protocol-brand b { display:block; font-family:var(--font-body); font-size:.65rem; letter-spacing:.12em; text-transform:uppercase } .protocol-nav { display:flex; gap:1.5rem } .protocol-nav a { color:var(--ink); font-family:var(--font-body); font-size:.7rem; text-decoration:none; text-transform:uppercase } .protocol-footer span { font-family:var(--font-display); font-weight:700 } @media(max-width:720px){.protocol-nav{display:flex;max-width:100%;overflow-x:auto;padding:.4rem 0}.protocol-nav a{border-left:2px solid var(--cobalt);min-width:max-content;padding-left:.5rem}}`,
  requiredData: [], requiredCapabilities: [],
};

shell.css += `.protocol-footer{display:flex;justify-content:space-between;gap:1rem;padding:1rem;border-top:1px solid var(--line)}.protocol-footer nav{display:flex;flex-wrap:wrap;gap:1rem}.protocol-footer a{color:var(--ink);text-decoration:none}`;

const home = {
  html: `<main class="protocol-home"><section class="day-frame"><aside id="time-arc" class="time-arc" data-cd-state-id="protocol-time" data-cd-state-type="enum" data-cd-state-initial="all" data-cd-state-values="all am mid pm" data-cd-bind-state="protocol-time" data-cd-bind-property="classToken"><h2>Assemble the daily protocol</h2><button value="all" data-cd-on="click" data-cd-action="state.set" data-cd-state="protocol-time"><b>24H</b> Full protocol</button><button value="am" data-cd-on="click" data-cd-action="state.set" data-cd-state="protocol-time"><b>AM</b> Prime</button><button value="mid" data-cd-on="click" data-cd-action="state.set" data-cd-state="protocol-time"><b>12</b> Sustain</button><button value="pm" data-cd-on="click" data-cd-action="state.set" data-cd-state="protocol-time"><b>PM</b> Restore</button></aside><figure class="protocol-image"><img data-cd-asset="hero" alt="Daily wellness protocol arranged in natural light"><figcaption>Daily foundations</figcaption></figure><div class="protocol-copy"><small>Evidence over noise</small><h1>Less guesswork. Better rhythm.</h1><p class="protocol-long-copy">A legible daily routine with live formats, merchant-authored serving information, and stock-aware purchase controls.</p><a data-cd-route="collection">Open the product ledger</a></div></section><section id="protocol-stack" class="protocol-stack"><header><h2>A routine with edges.</h2><p>Each time block opens to current products and formats.</p></header><div class="stack-steps"><article><b>AM</b><h3>Prime</h3><p>Foundation and hydration.</p></article><article><b>AM</b><h3>Protect</h3><p>Targeted daily formats.</p></article><article><b>12</b><h3>Sustain</h3><p>Portable midday support.</p></article><article><b>PM</b><h3>Restore</h3><p>Repeatable evening rhythm.</p></article></div><div class="protocol-products" data-cd-repeat="featured.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h3 data-cd-text="product.title"></h3><p class="protocol-long-copy" data-cd-text="product.description"></p><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">View protocol facts</a></article></div></section><section data-cd-repeat="featured.products"><aside data-cd-key="product.id" data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="panel" data-cd-theme-tokens="ink cobalt paper"></aside></section><button data-cd-on="click" data-cd-action="scroll.to" data-cd-target="protocol-stack">Review protocol stack</button></main>`,
  css: `.day-frame { display:grid; grid-template-columns:14rem minmax(24rem,1.1fr) minmax(20rem,.9fr); min-height:42rem } .time-arc { background:var(--ink); color:var(--paper); padding:2rem } .time-arc[data-cd-class-token="am"] { box-shadow:inset 5px 0 var(--cobalt) } .time-arc[data-cd-class-token="mid"] { box-shadow:inset 5px 0 var(--fog) } .time-arc[data-cd-class-token="pm"] { box-shadow:inset 5px 0 var(--muted) } .time-arc h2 { font-size:1.2rem } .time-arc button { background:transparent; border:0; border-bottom:1px solid var(--muted); color:var(--paper); display:grid; grid-template-columns:3rem 1fr; padding:1rem 0; text-align:left; width:100% } .protocol-image img { height:39rem; object-fit:cover; width:100% } .protocol-image figcaption { background:var(--cobalt); color:var(--paper); font-family:var(--font-body); padding:1rem } .protocol-copy { align-content:center; display:grid; padding:clamp(2rem,5vw,5rem) } .protocol-copy h1 { font-size:clamp(3rem,4.2vw,3.8rem); line-height:.9; overflow-wrap:anywhere } .protocol-stack { scroll-margin-top:2rem } .protocol-stack h2 { font-size:clamp(3rem,6vw,6rem); line-height:.88 } .stack-steps { display:grid; grid-template-columns:repeat(4,1fr) } .stack-steps article { border:1px solid var(--line); min-height:15rem; padding:1.5rem } .stack-steps article:nth-child(3) { background:var(--cobalt); color:var(--paper) } .protocol-products { display:flex; overflow:auto;scroll-snap-type:x mandatory } .protocol-products article { min-width:18rem;scroll-snap-align:start } .protocol-products img { aspect-ratio:4 / 5; object-fit:cover; width:100% } @media(max-width:900px){ .day-frame { grid-template-columns:1fr } .time-arc { display:grid; grid-template-columns:repeat(4,8rem); overflow:auto; padding:1.5rem } .time-arc h2 { grid-column:1 / -1; margin:0 0 .5rem } .time-arc button { min-width:0 } .protocol-image img { height:27rem } .stack-steps { display:flex; overflow:auto;scroll-snap-type:x mandatory } .stack-steps article { min-width:70vw;scroll-snap-align:center } } @media(prefers-reduced-motion:reduce){.protocol-products,.stack-steps{scroll-snap-type:none}}`,
  requiredData: [], requiredCapabilities: [],
};

home.html = home.html.replace(
  `class="stack-steps"`,
  `class="stack-steps" tabindex="0" aria-label="Daily protocol steps"`,
);

const collection = {
  html: `<main class="product-ledger"><header class="ledger-intro"><div><small>Timed product ledger</small><h1 data-cd-text="collection.title"></h1><p class="protocol-long-copy" data-cd-text="collection.description"></p></div><img data-cd-src="collection.image" data-cd-alt="collection.title"></header><nav class="time-filters" aria-label="Protocol time filters"><button value="am" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">AM</button><button value="midday" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Midday</button><button value="pm" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">PM</button><button value="vegan" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Vegan</button><button value="relevance" data-cd-on="click" data-cd-action="collection.sort">Protocol order</button></nav><section class="ledger-rows" data-cd-repeat="collection.products"><article data-cd-key="product.id"><span>Time block</span><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p class="protocol-long-copy" data-cd-text="product.description"></p><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">View timing and dose</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline" data-cd-theme-tokens="ink cobalt paper"></div></article></section><p class="protocol-empty">No live products match this protocol window. Clear a time filter to continue.</p></main>`,
  css: `.ledger-intro { display:grid; grid-template-columns:1.1fr .9fr; min-height:21rem } .ledger-intro h1 { font-size:clamp(4rem,8vw,7rem); line-height:.84 } .ledger-intro img { height:21rem; object-fit:cover; width:100% } .time-filters { display:flex; gap:.5rem; overflow:auto; padding:1rem } .time-filters button { background:var(--fog); border:1px solid var(--ink); font-family:var(--font-body); padding:.8rem 1rem } .ledger-rows img { height:7rem; object-fit:cover; width:5rem } .ledger-rows h2 { font-size:1.2rem } .ledger-rows p { font-family:var(--font-body) } .protocol-empty { border:1px dashed var(--cobalt); padding:2rem } @media(max-width:760px){ .ledger-intro { grid-template-columns:1fr } .ledger-intro img { height:15rem } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "collection" as const,
};

const product = {
  html: `<main class="protocol-record"><section id="protocol-gallery" class="protocol-gallery"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><div data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"></figure></div></section><article id="protocol-facts" class="protocol-facts" data-cd-state-id="facts-open" data-cd-state-type="boolean" data-cd-state-initial="false" data-cd-bind-state="facts-open" data-cd-bind-property="expanded"><small>Protocol evidence record</small><h1 data-cd-text="product.title"></h1><p data-cd-money="product.price"></p><b data-cd-text="product.availability"></b><p class="protocol-long-copy" data-cd-text="product.description"></p><p>Unavailable protocols keep their evidence visible while trusted purchase controls prevent invalid additions.</p><button value="timing" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="protocol-facts">Timing and serving</button><button value="formulation" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="protocol-facts">Formulation facts</button><button value="warnings" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="protocol-facts">Warnings and standards</button><div class="format-ledger" data-cd-repeat="product.variants"><span data-cd-key="variant.id" data-cd-text="variant.title"></span></div><div id="format-picker" data-cd-slot="variantPicker" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="ink cobalt paper"></div><div data-cd-slot="addToCart" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="ink cobalt paper"></div></article><section class="adjacent-protocols" data-cd-repeat="related.products"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><p class="protocol-long-copy" data-cd-text="product.description"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Next time block</a></article></section></main>`,
  css: `.protocol-gallery img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .protocol-facts h1 { font-size:clamp(3.5rem,7vw,6.8rem); line-height:.86 } .protocol-facts p { max-width:45rem } .protocol-facts button { background:transparent; border:0; border-top:1px solid var(--line); font-family:var(--font-body); padding:1rem; text-align:left; width:100% } .protocol-facts[aria-expanded="true"] { border-left:5px solid var(--cobalt); padding-left:1rem } .format-ledger span { border:1px solid var(--ink); display:inline-block; padding:.75rem; width:auto } .adjacent-protocols h2 { font-size:1.3rem }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "product" as const,
};

const search = {
  html: `<main class="protocol-search"><header><small>Evidence and product search</small><h1>Search ingredient, format, timing, or product.</h1><p data-cd-text="search.query"></p></header><div class="protocol-query" role="search"><input aria-label="Protocol search" type="search" name="q" value="" placeholder="Ingredient, format, timing, or product" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Search ledger</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear query</button></div><section class="search-ledger" data-cd-repeat="search.results"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p class="protocol-long-copy" data-cd-text="product.description"></p><p data-cd-money="product.price"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Open protocol facts</a></article></section><p class="protocol-empty">No protocol result. Try a time, form, or product name.</p></main>`,
  css: `.protocol-search h1 { font-size:clamp(3.2rem,7vw,6.5rem); line-height:.9; max-width:13ch } .protocol-query { display:flex; gap:.5rem } .protocol-query input, .protocol-query button { background:var(--cobalt); border:1px solid var(--ink); color:var(--paper); font-family:var(--font-body); padding:.8rem } .search-ledger { display:grid; grid-template-columns:repeat(2,1fr) } .search-ledger img { height:8rem; object-fit:cover; width:6rem } .search-ledger h2 { font-size:1.3rem } @media(max-width:760px){ .search-ledger { grid-template-columns:1fr } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "search" as const,
};

const cart = {
  html: `<main class="routine-bag"><header><small>Current protocol stack</small><h1>Routine bag</h1><p><span data-cd-text="cart.count"></span> protocol lines</p></header><section class="routine-lines" data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><p data-cd-text="cartLine.quantity"></p><p data-cd-money="cartLine.unitPrice"></p><p data-cd-money="cartLine.total"></p><div data-cd-slot="cartLineControls" data-cd-host-size="inline" data-cd-theme-tokens="ink cobalt paper"></div></article></section><p class="protocol-empty">Your routine bag is empty. Choose a time block to begin.</p><aside data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="ink cobalt paper"></aside></main>`,
  css: `.routine-bag h1 { font-size:clamp(3.5rem,8vw,7rem); line-height:.86 } .routine-lines h2 { font-size:1.3rem } .routine-lines p { font-family:var(--font-body) } .protocol-empty { border:1px dashed var(--cobalt); padding:2rem }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "cart" as const,
};

const checkout = {
  html: `<header class="protocol-checkout"><small>Secure protocol checkout</small><h1 data-cd-text="store.name"></h1><p>The authoritative summary leads, followed by contact, delivery, consent, and payment in protocol order.</p></header><aside class="timing-note"><b>Timing remains attached</b><p>Format and merchant-authored serving information continue into confirmation.</p></aside><footer data-cd-policy-links></footer>`,
  css: `.protocol-checkout { padding:48px; background-color:var(--paper); color:var(--ink) } .protocol-checkout h1 { font-family:var(--font-display); font-size:54px; line-height:.9 } .timing-note { margin:24px 48px; padding:18px; background-color:var(--soft); border-width:1px; border-style:solid; border-color:var(--ink) }`,
  layout: { columnMode: "summaryFirst" as const, sectionOrder: ["summary", "contact", "shipping", "delivery", "consent", "payment"], spacingTokenId: "space-protocol", surfaceTokenIds: ["paper", "ink", "cobalt", "soft"] },
} satisfies RecipeConfig<"daily-protocol">["surfaces"]["checkout"]["source"];

const config = {
  templateId: "daily-protocol", templateVersion: 1,
  concept: { name: "Daily Protocol", rationale: "A timed ledger organizes wellness products by when and how they are used.", noveltySignature: ["time arc", "protocol stack", "dense dose ledger"] },
  designSystem: { displayFontId: "inter", bodyFontId: "ibm-plex-mono", tokens: { fog: "#e9eeeb", paper: "#f8faf7", ink: "#111914", cobalt: "#2848d8", soft: "#b8c7ef", line: "#68736c", muted: "#68736c", "space-protocol": "20px" }, breakpoints: { mobile: 720, wide: 1180 }, iconStyle: "time block markers and dosage data glyphs", motionStyle: "routine timeline switching with direct state feedback and restrained reveals", globalCss: `.protocol-long-copy { overflow-wrap: anywhere }` },
  archetype: { composition: "protocol-ledger", hero: "time-of-day-protocol", scroll: "routine-timeline", cards: "protocol-stacks", iconography: ["time block markers", "dosage data glyphs"] },
  surfaces: {
    shell: { signature: "disciplined protocol masthead connecting evidence search and routine bag", source: shell },
    home: { signature: "time-of-day arc beside product image and assembled protocol sequence", source: home },
    collection: { signature: "time filters feeding a dense dosage and availability product ledger", source: collection },
    product: { signature: "protocol image record paired with timing, serving, and formulation facts", source: prependRecipeLandmark(product, `<aside class="protocol-sequence"><b>AM</b><b>12</b><b>PM</b></aside>`) },
    search: { signature: "evidence query header above compact protocol ledger results", source: prependRecipeLandmark(search, `<nav class="evidence-path" aria-label="Evidence search path"><span>Query</span><span>Format</span><span>Timing</span></nav>`) },
    cart: { signature: "routine stack lines with trusted quantity controls and protocol summary", source: prependRecipeLandmark(cart, `<aside class="routine-clock"><small>24 hour stack</small></aside>`) },
    checkout: { signature: "summary-first protocol checkout retaining timing and serving context", source: wrapRecipeComposition(checkout, "aside", "protocol-checkout-frame") },
  }, assets: DAILY_PROTOCOL_ASSETS,
} satisfies RecipeConfig<"daily-protocol">;

export const DAILY_PROTOCOL_RECIPE = defineRecipe(config);

export const DAILY_PROTOCOL_BUNDLE = DAILY_PROTOCOL_RECIPE.bundle;
