import { defineRecipe, type RecipeConfig } from "../factory";
import { RITUAL_ALMANAC_ASSETS } from "./assets";

const config = {
  templateId: "ritual-almanac", templateVersion: 1,
  concept: { name: "Ritual Almanac", rationale: "An editorial pantry organized by hour, flavor chapter, and recurring ritual instead of benefit-card claims.", noveltySignature: ["ritual-time-wheel", "almanac-chapters", "cadence-led-pantry"] },
  designSystem: {
    displayFontId: "fraunces", bodyFontId: "inter",
    tokens: { milk: "#f4efe4", ink: "#26382d", moss: "#355944", leaf: "#a8bf7e", plum: "#8f4564", sun: "#ef8b45", paper: "#e5dccb", "chapter-space": "26px" },
    breakpoints: { compact: 820, wide: 1200 }, iconStyle: "time-of-day marks and restrained flavor-note symbols", motionStyle: "chapter reveals with ritual-time tab transitions",
    globalCss: `.almanac-title{font-family:var(--font-display);font-weight:600;letter-spacing:-.04em;line-height:.9}.ritual-mark{font-family:var(--font-body);font-size:.68rem;letter-spacing:.15em;text-transform:uppercase}`,
  },
  archetype: { composition: "editorial-almanac", hero: "ritual-time-hero", scroll: "almanac-chapters", cards: "ritual-entries", iconography: ["time ritual marks", "flavor note symbols"] },
  surfaces: {
    shell: { signature: "quiet almanac masthead with moment index, pantry search, and case drawer", source: {
      html: `<header class="almanac-shell"><a class="almanac-title" data-cd-route="home" data-cd-text="store.name">Ritual Almanac</a><nav aria-label="Almanac navigation"><a data-cd-route="collection">Pantry</a><a data-cd-route="home">By moment</a><a data-cd-route="search">Search</a><a data-cd-route="cart">Case</a></nav></header><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="milk moss plum"></aside>`,
      css: `.almanac-shell nav{display:flex;gap:1.25rem}.almanac-shell nav a{font-size:.7rem;text-transform:uppercase}.almanac-title{font-size:1.8rem}`, requiredData: [], requiredCapabilities: [],
    } },
    home: { signature: "arched editorial hero opening into a time-wheel chapter and flavor-story provisions", source: {
      html: `<main><section class="ritual-hero"><div class="ritual-copy resilient-copy"><small class="ritual-mark">Daily provisions</small><h1 class="almanac-title">Good things at the right hour.</h1><p>Functional drinks and pantry staples mapped to the natural shape of a day.</p><a data-cd-route="collection">Open the pantry</a></div><figure class="ritual-image"><img data-cd-asset="hero" alt="Specialty beverages and ingredients arranged for a daily ritual" width="1600" height="1200"></figure></section><section class="time-chapter"><nav class="time-wheel" aria-label="Ritual time"><button data-cd-on="click" data-cd-action="tabs.select" data-cd-target="moment">Wake</button><button data-cd-on="click" data-cd-action="tabs.select" data-cd-target="moment">Focus</button><button data-cd-on="click" data-cd-action="tabs.select" data-cd-target="moment">Recover</button><button data-cd-on="click" data-cd-action="tabs.select" data-cd-target="moment">Unwind</button></nav><article id="moment" class="moment-copy resilient-copy"><small class="ritual-mark">Wake ritual</small><h2 class="almanac-title">Begin bright, not rushed.</h2><p>Choose the hour first, then find the flavor and format that belongs there.</p></article></section><section data-cd-repeat="featured.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="600" height="760"><h2 data-cd-text="product.title"></h2><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Read ritual entry</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="pantry-empty resilient-copy">No provisions match this ritual. Browse another hour or flavor chapter.</p></main>`,
      css: `.ritual-hero{display:grid;grid-template-columns:1fr 1fr;min-height:75dvh}.ritual-copy{align-self:center;padding:clamp(2rem,7vw,7rem)}.ritual-copy h1{font-size:clamp(4rem,9vw,9rem);max-width:8ch}.ritual-image{margin:1.25rem;overflow:hidden;border-radius:50% 50% 10px 10px}.ritual-image img{display:block;width:100%;height:72dvh;object-fit:cover}.time-chapter{display:grid;grid-template-columns:.7fr 1.3fr;gap:5vw;padding:clamp(2rem,7vw,7rem);background:var(--paper)}.time-wheel{display:grid;grid-template-columns:1fr 1fr;align-content:center;gap:.75rem}.time-wheel button{padding:1rem;border:1px solid var(--moss);border-radius:999px;background:var(--milk)}.moment-copy h2{font-size:clamp(3.5rem,7vw,7rem)}.ritual-copy,.moment-copy,.pantry-empty,.resilient-copy{overflow-wrap:anywhere}.pantry-empty{padding:2rem}@media(max-width:820px){.ritual-hero,.time-chapter{grid-template-columns:1fr}.ritual-image img{height:52dvh}}`, requiredData: [], requiredCapabilities: [],
    } },
    collection: { signature: "chapter-frontispiece collection with pill facets and arched ritual-entry catalog", source: {
      html: `<main><header class="chapter-front resilient-copy"><small class="ritual-mark">The live pantry</small><h1 class="almanac-title" data-cd-text="collection.title"></h1><p data-cd-text="collection.description"></p><b data-cd-text="collection.productCount"></b></header><nav class="chapter-filters"><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="moment">Wake</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="moment">Focus</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="moment">Unwind</button><button data-cd-on="click" data-cd-action="collection.sort">Almanac order</button></nav><section data-cd-repeat="collection.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="620" height="760"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Open entry</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="chapter-empty resilient-copy">No provisions match this ritual. Clear a moment filter.</p><p class="sold-entry">Sold out provisions stay in the almanac for flavor reference.</p></main>`,
      css: `.chapter-front{padding:clamp(2rem,7vw,7rem);background:var(--paper)}.chapter-front h1{font-size:clamp(4rem,9vw,9rem)}.chapter-filters{position:sticky;top:0;display:flex;gap:.5rem;padding:1rem;background:var(--milk);overflow:auto}.chapter-filters button{padding:.75rem 1rem;border:1px solid var(--moss);border-radius:999px;background:transparent}.chapter-front,.chapter-empty,.resilient-copy{overflow-wrap:anywhere}.chapter-empty,.sold-entry{padding:1.5rem}`, requiredData: [], requiredCapabilities: [],
    } },
    product: { signature: "arched ingredient gallery beside long-form flavor entry and subscription-cadence purchase chapter", source: {
      html: `<main><section class="flavor-gallery" data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="900" height="1050"></figure></section><header class="ritual-entry resilient-copy"><small class="ritual-mark">Flavor and function</small><h1 class="almanac-title" data-cd-text="product.title"></h1><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><h2>Subscription cadence</h2><p>Choose a one-time pantry addition or the recurring rhythm offered by the live variant set.</p><p>Sold out formats remain visible so serving and cadence notes still make sense.</p></header><section data-cd-repeat="product.variants"><div data-cd-key="variant.id"><b data-cd-text="variant.title"></b><span data-cd-text="variant.availability"></span><strong data-cd-money="variant.price"></strong></div></section><div data-cd-slot="variantPicker" data-cd-host-size="block" data-cd-theme-tokens="milk moss plum"></div><div data-cd-slot="addToCart" data-cd-host-size="block" data-cd-theme-tokens="milk moss plum"></div></main>`,
      css: `.flavor-gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:.5rem;padding:.5rem}.flavor-gallery figure{margin:0}.flavor-gallery img{display:block;width:100%;height:68dvh;object-fit:cover;border-radius:45% 45% 8px 8px}.ritual-entry{padding:clamp(2rem,6vw,6rem);max-width:66rem}.ritual-entry h1{font-size:clamp(4rem,8vw,8rem)}.ritual-entry,.resilient-copy{overflow-wrap:anywhere}@media(max-width:820px){.flavor-gallery{grid-template-columns:1fr}.flavor-gallery img{height:50dvh}}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "product",
    } },
    search: { signature: "serif pantry query opening into compact flavor-note result chapters and gentle empty state", source: {
      html: `<main><header class="pantry-query resilient-copy"><small class="ritual-mark">Search flavor, moment, or format</small><h1 class="almanac-title" data-cd-text="search.query">Search the almanac</h1><button data-cd-on="click" data-cd-action="search.submit">Find provisions</button><button data-cd-on="click" data-cd-action="search.clear">Clear search</button></header><section data-cd-repeat="search.results"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><a data-cd-route="product" data-cd-param-handle="product.handle">Read result</a></article></section><p class="search-empty resilient-copy">No provisions match this ritual. Try a flavor, moment, or format.</p></main>`,
      css: `.pantry-query{padding:clamp(2rem,8vw,8rem);background:var(--paper)}.pantry-query h1{font-size:clamp(4rem,9vw,9rem)}.pantry-query button{padding:.8rem;margin-right:.5rem;border:1px solid var(--moss);border-radius:999px;background:transparent}.pantry-query,.search-empty,.resilient-copy{overflow-wrap:anywhere}.search-empty{padding:2rem}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "search",
    } },
    cart: { signature: "pantry-case ledger with softly arched rhythm, quantity controls, and cadence-aware summary", source: {
      html: `<main><header class="case-head resilient-copy"><small class="ritual-mark">Your pantry case</small><h1 class="almanac-title">A week by the bottle</h1><span data-cd-text="cart.count"></span></header><section data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><span data-cd-text="cartLine.quantity"></span><b data-cd-money="cartLine.unitPrice"></b><strong data-cd-money="cartLine.total"></strong><div data-cd-slot="cartLineControls" data-cd-host-size="inline"></div></article></section><aside class="case-total resilient-copy"><span>Subtotal</span><b data-cd-money="cart.subtotal"></b><span>Total</span><strong data-cd-money="cart.total"></strong></aside><div data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="milk moss plum"></div><p class="case-empty resilient-copy">Your pantry case is empty. Begin with the hour you want to support.</p></main>`,
      css: `.case-head{padding:clamp(2rem,7vw,7rem);background:var(--moss);color:var(--milk)}.case-head h1{font-size:clamp(4rem,8vw,8rem)}.case-total{display:grid;grid-template-columns:1fr auto;gap:1rem;padding:2rem;max-width:38rem;margin-left:auto}.case-head,.case-total,.case-empty,.resilient-copy{overflow-wrap:anywhere}.case-empty{padding:2rem}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "cart",
    } },
    checkout: { signature: "editorial pantry checkout with softly separated summary and subscription-delivery trust notes", source: {
      html: `<header class="checkout-almanac"><small>Final pantry chapter</small><h1 data-cd-text="store.name">Ritual Almanac</h1><p>Review quantities and cadence before the platform completes delivery and payment.</p></header><aside class="delivery-note"><b>Small-batch dispatch</b><span>Cadence confirmed at review</span><span>Secure payment</span></aside><footer data-cd-policy-links></footer>`,
      css: `.checkout-almanac{padding:48px;max-width:760px}.checkout-almanac h1{font-size:64px}.delivery-note{display:grid;gap:12px;padding:30px;background-color:var(--paper);border-radius:24px}`,
      layout: { columnMode: "summaryAside", sectionOrder: ["contact", "shipping", "delivery", "consent", "payment", "summary"], spacingTokenId: "chapter-space", surfaceTokenIds: ["milk", "paper", "moss", "plum"] },
    } },
  }, assets: RITUAL_ALMANAC_ASSETS,
} satisfies RecipeConfig<"ritual-almanac">;

export const RITUAL_ALMANAC_RECIPE = defineRecipe(config);
export const RITUAL_ALMANAC_BUNDLE = RITUAL_ALMANAC_RECIPE.bundle;
