import type { BindingScopeKind } from "~/lib/storefront-compiler/bindings";
import type { RouteSource } from "~/lib/storefront-compiler/compile";
import { videoFragment } from "../library/media";
import { compileRecipeConfig, type RecipeConfig } from "../factory";
import { HAVEN_ASSETS } from "./assets";

function route(html: string, css: string, rootScopeKind?: BindingScopeKind): RouteSource {
  return { html, css, requiredData: [], requiredCapabilities: [], ...(rootScopeKind ? { rootScopeKind } : {}) };
}

const hero = videoFragment({ className: "haven-film", posterAssetKey: "hero-poster", webmAssetKey: "hero-webm", mp4AssetKey: "hero-mp4" });
const contextFilm = videoFragment({ className: "haven-film", posterAssetKey: "hero-alt-poster", webmAssetKey: "hero-alt-webm", mp4AssetKey: "hero-alt-mp4" });
const detailFilm = videoFragment({ className: "haven-film", posterAssetKey: "pdp-detail-poster", webmAssetKey: "pdp-detail-webm", mp4AssetKey: "pdp-detail-mp4" });

const base = `.haven-display{font-family:var(--font-display);font-weight:400;letter-spacing:-.055em;line-height:.9}.haven-button{display:inline-flex;min-height:44px;align-items:center;padding:.8rem 1.15rem;border:1px solid var(--walnut);background:var(--walnut);color:var(--ash);text-decoration:none}.haven-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--line)}.haven-card{display:grid;gap:.8rem;padding:1rem;background:var(--ash)}.haven-card img{width:100%;aspect-ratio:4/5;object-fit:cover;background:var(--clay)}.haven-card a{color:inherit;text-decoration:none}.haven-empty{padding:2rem}@media(max-width:720px){.haven-grid{grid-template-columns:1fr}}`;
const liveCards = `<div class="haven-grid" data-cd-repeat="featured.products"><article class="haven-card" data-cd-key="product.id"><a data-cd-route="product" data-cd-param-handle="product.handle"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="720" height="900"><h3 data-cd-text="product.title"></h3></a><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span></article></div>`;
const measurementChecklist = `<section class="haven-measure"><header><span>Room-fit evidence</span><h2 class="haven-display">Measure first. Decide with facts.</h2><p>No room-fit result is calculated here because dimensions are not available as a verified storefront field. Compare your measurements only with dimensions the merchant has supplied in a live product description.</p></header><div id="haven-room-check" class="haven-room-check" data-cd-state-id="haven-room-step" data-cd-state-type="index" data-cd-state-initial="0" data-cd-state-min="0" data-cd-state-max="3" data-cd-bind-state="haven-room-step" data-cd-bind-property="activeIndex"><article><b>1 / Measure the room</b><p>Record the available width, depth, access path, and clearance yourself.</p></article><article><b>2 / Read the live product</b><p>Look for merchant-supplied dimensions in the product description. Missing dimensions remain missing.</p></article><article><b>3 / Choose a real variant</b><p>Use only the available options shown by the protected product controls.</p></article><article><b>4 / Confirm checkout</b><p>Delivery timing appears only when checkout provides it.</p></article></div><nav><button data-cd-on="click" data-cd-action="state.decrement" data-cd-state="haven-room-step">Previous room check</button><button data-cd-on="click" data-cd-action="state.increment" data-cd-state="haven-room-step">Next room check</button></nav><a class="haven-button" data-cd-route="collection">Browse live furniture</a></section>`;

export const HAVEN_RECIPE_CONFIG = {
  templateId: "haven",
  templateVersion: 1,
  concept: { name: "Haven", rationale: "A spatially quiet furniture storefront that keeps room planning grounded in merchant-supplied catalog evidence.", noveltySignature: ["room-scale-frame", "measurement-checklist", "material-tray"] },
  designSystem: {
    displayFontId: "fraunces", bodyFontId: "inter",
    tokens: { ash: "#eee9df", walnut: "#3b2a21", clay: "#b8795a", moss: "#68715b", paper: "#faf8f3", ink: "#251f1b", line: "#bcb3a8", "space-room": "28px" },
    breakpoints: { compact: 720, wide: 1280 }, iconStyle: "quiet floor-plan marks and joinery lines", motionStyle: "slow spatial reveals with static reduced-motion fallback", globalCss: "",
  },
  archetype: { composition: "spatial-studies", hero: "material-room-hero", scroll: "spatial-quiet", cards: "material-panels", iconography: ["floor-plan marks", "joinery lines"] },
  surfaces: {
    shell: { signature: "quiet timber masthead with live cart and policy access", source: route(`<header class="haven-nav"><a data-cd-route="home"><b data-cd-text="store.name"></b></a><nav><a data-cd-route="collections">Rooms</a><a data-cd-route="collection">Furniture</a><a data-cd-route="story">Materials</a><a data-cd-route="search">Search</a><a data-cd-route="cart">Cart <span data-cd-text="cart.count"></span></a></nav></header><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="ash walnut clay"></aside><footer class="haven-footer"><span data-cd-text="store.name"></span><nav data-cd-policy-links></nav></footer>`, `.haven-nav,.haven-footer{display:flex;justify-content:space-between;gap:1.5rem;padding:1.2rem 2rem;background:var(--ash);color:var(--walnut);border-bottom:1px solid var(--line)}.haven-nav nav{display:flex;flex-wrap:wrap;gap:1.25rem}.haven-nav a,.haven-footer a{color:inherit;text-decoration:none}@media(max-width:720px){.haven-nav{display:grid}}`) },
    home: { signature: "room-scale hero, material proof, live furniture rail, and evidence-only measurement checklist", source: route(`<main class="haven-home"><section class="haven-hero"><div class="haven-hero-film">${hero.html}</div><div class="haven-frame" aria-hidden="true"></div><article><span>Furniture / space / lived scale</span><h1 class="haven-display">Room to live<br>with less noise.</h1><p>Browse the live catalog, then verify dimensions, options, price, and availability from each merchant-supplied product page.</p><a class="haven-button" data-cd-route="collection">Enter the collection</a></article></section><aside class="haven-proof">LIVE PRODUCTS <span>•</span> CURRENT PRICES <span>•</span> MERCHANT-SUPPLIED DETAILS</aside><section class="haven-catalog"><header><span>Current collection</span><h2 class="haven-display">Objects for actual rooms.</h2></header>${liveCards}<p class="haven-empty" data-cd-empty-state>No furniture is available yet.</p></section>${measurementChecklist}</main>`, `${base}.haven-home{background:var(--paper);color:var(--ink)}.haven-hero{position:relative;display:grid;align-items:end;min-height:86dvh;overflow:hidden;padding:clamp(2rem,7vw,7rem);background:linear-gradient(120deg,var(--ash),var(--clay));color:var(--walnut)}.haven-hero-film,.haven-film{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.haven-hero article{position:relative;z-index:2;max-width:52rem}.haven-hero h1{font-size:clamp(4.5rem,10vw,9rem);margin:.2em 0}.haven-frame{position:absolute;right:8%;top:10%;width:38%;height:68%;border:1px solid var(--walnut);box-shadow:-3rem 3rem 0 var(--ash)}.haven-proof{display:flex;justify-content:space-around;gap:2rem;padding:1rem;background:var(--walnut);color:var(--ash);font-size:.72rem;letter-spacing:.12em}.haven-catalog,.haven-measure{padding:clamp(3rem,7vw,7rem) clamp(1rem,4vw,4rem)}.haven-catalog h2,.haven-measure h2{font-size:clamp(3.5rem,7vw,7rem);margin:.2em 0}.haven-measure{display:grid;grid-template-columns:1fr 1fr;gap:3rem;background:var(--clay)}.haven-room-check{min-height:12rem;padding:1.5rem;background:var(--ash)}.haven-measure nav{display:flex;gap:.5rem}.haven-measure button{min-height:44px;padding:.7rem 1rem;border:1px solid var(--walnut);background:transparent;color:var(--walnut)}@media(max-width:720px){.haven-measure{grid-template-columns:1fr}.haven-frame{right:-10%;width:58%}.haven-proof{overflow:auto;justify-content:flex-start}}@media(prefers-reduced-motion:reduce){.haven-film,.haven-frame,.haven-hero article{animation:none;transition:none;transform:none}}`) },
    collections: { signature: "single honest all-furniture directory with live product evidence", source: route(`<main class="haven-list"><header><span>Catalog directory</span><h1 class="haven-display">Everything currently in the room.</h1><p>Browse the merchant's live furniture catalog without inferred room labels.</p><a class="haven-button" data-cd-route="collection">All furniture</a></header>${liveCards}</main>`, `${base}.haven-list{padding:clamp(2rem,7vw,7rem);background:var(--paper);color:var(--ink)}.haven-list h1{font-size:clamp(4rem,9vw,8rem)}`) },
    collection: { signature: "live collection matrix using merchant imagery, descriptions, prices, and availability", source: route(`<main class="haven-list"><header><span>Live collection</span><h1 class="haven-display" data-cd-text="collection.title"></h1><p data-cd-text="collection.description"></p><b><span data-cd-text="collection.productCount"></span> products</b></header><div class="haven-grid" data-cd-repeat="collection.products"><article class="haven-card" data-cd-key="product.id"><a data-cd-route="product" data-cd-param-handle="product.handle"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="720" height="900"><h2 data-cd-text="product.title"></h2></a><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span></article></div><p class="haven-empty" data-cd-empty-state>No products are available in this collection.</p></main>`, `${base}.haven-list{padding:clamp(2rem,7vw,7rem);background:var(--paper);color:var(--ink)}.haven-list h1{font-size:clamp(4rem,9vw,8rem)}`, "collection") },
    product: { signature: "merchant-media room frame with live description, variants, and protected sticky purchase", source: route(`<main class="haven-product"><section class="haven-gallery"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="1100" height="1100"><div data-cd-repeat="product.images"><img data-cd-key="product.primaryImage" data-cd-src="product.primaryImage" data-cd-alt="product.title" width="760" height="760"></div><div class="haven-detail-film">${detailFilm.html}</div></section><article><span>Live product record</span><h1 class="haven-display" data-cd-text="product.title"></h1><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><p data-cd-text="product.description"></p><aside><b>Room-fit check</b><p>No room-fit result is calculated here. Use only dimensions explicitly supplied in the product description and compare them with your own room measurements.</p><p>No AR or swatch availability is inferred. Available choices appear only in the live variants below.</p></aside><div data-cd-repeat="product.variants"><div data-cd-key="variant.id"><b data-cd-text="variant.title"></b><span data-cd-money="variant.price"></span><span data-cd-text="variant.availability"></span></div></div><nav data-cd-policy-links></nav></article></main><div data-cd-slot="variantPicker" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="ash walnut clay"></div><div data-cd-slot="addToCart" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="ash walnut clay"></div>`, `${base}.haven-product{display:grid;grid-template-columns:1.2fr .8fr;background:var(--walnut)}.haven-gallery{display:grid;gap:1px;background:var(--line)}.haven-gallery img{width:100%;aspect-ratio:1;object-fit:cover}.haven-detail-film{position:relative;min-height:320px;background:linear-gradient(135deg,var(--ash),var(--clay))}.haven-product>article{position:sticky;top:0;align-self:start;display:grid;gap:1.2rem;min-height:100dvh;padding:clamp(2rem,5vw,5rem);background:var(--ash)}.haven-product h1{font-size:clamp(3.5rem,7vw,7rem);margin:.2em 0}@media(max-width:720px){.haven-product{grid-template-columns:1fr}.haven-product>article{position:static;min-height:auto}}@media(prefers-reduced-motion:reduce){.haven-film{animation:none;transition:none}}`, "product") },
    search: { signature: "restrained search workspace with live furniture results and neutral recovery", source: route(`<main class="haven-list"><header><span>Catalog search</span><h1 class="haven-display">Find an object.</h1><div role="search"><input aria-label="Search furniture" type="search" name="q" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Search</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear</button></div><p data-cd-text="search.query"></p></header><div class="haven-grid" data-cd-repeat="search.results"><article class="haven-card" data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="360" height="450"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">View product</a></article></div><p class="haven-empty" data-cd-empty-state>No products matched. Try another search.</p></main>`, `${base}.haven-list{padding:clamp(2rem,7vw,7rem);background:var(--paper)}.haven-list input,.haven-list button{min-height:44px;padding:.75rem;border:1px solid var(--walnut)}`, "search") },
    story: { signature: "lived-room film beside an honest material and evidence statement", source: route(`<main class="haven-story"><section>${contextFilm.html}</section><article><span>Materials / evidence</span><h1 class="haven-display">Live with what is known.</h1><p><span data-cd-text="store.name"></span> presents current product imagery, descriptions, prices, availability, and options without inventing specifications.</p><p>For material, finish, care, or construction facts, use only the merchant-supplied product description.</p><a class="haven-button" data-cd-route="collection">Browse live furniture</a></article></main><nav data-cd-policy-links></nav>`, `${base}.haven-story{display:grid;grid-template-columns:1.2fr .8fr;min-height:75dvh}.haven-story>section{position:relative;background:var(--walnut)}.haven-story>article{padding:clamp(2rem,7vw,7rem);background:var(--clay)}.haven-story h1{font-size:clamp(4rem,8vw,8rem)}@media(max-width:720px){.haven-story{grid-template-columns:1fr}.haven-story>section{min-height:50dvh}}@media(prefers-reduced-motion:reduce){.haven-film{animation:none;transition:none}}`) },
    cart: { signature: "quiet cart ledger with live totals, protected controls, and checkout-only delivery timing", source: route(`<main class="haven-cart"><header><span>Cart / current room</span><h1 class="haven-display">Objects selected.</h1><b><span data-cd-text="cart.count"></span> items</b></header><section data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><span data-cd-text="cartLine.quantity"></span><span data-cd-money="cartLine.unitPrice"></span><strong data-cd-money="cartLine.total"></strong></article></section><aside><span>Subtotal</span><b data-cd-money="cart.subtotal"></b><span>Total</span><strong data-cd-money="cart.total"></strong></aside><p>Delivery timing appears only when checkout provides it.</p><p class="haven-empty" data-cd-empty-state>Your cart is empty.</p></main><section data-cd-repeat="cart.lines"><div data-cd-key="cartLine.id" data-cd-slot="cartLineControls" data-cd-host-size="inline"></div></section><div data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="ash walnut clay"></div>`, `${base}.haven-cart{padding:clamp(2rem,7vw,7rem);background:var(--paper)}.haven-cart h1{font-size:clamp(4rem,9vw,8rem)}.haven-cart article{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:1rem;padding:1rem;border-bottom:1px solid var(--line)}@media(max-width:720px){.haven-cart article{grid-template-columns:1fr 1fr}}`, "cart") },
    checkout: { signature: "restrained checkout decoration deferring delivery facts to platform checkout", source: { html: `<header class="haven-checkout"><span>Secure checkout</span><h1 data-cd-text="store.name"></h1><p>Delivery timing appears only when checkout provides it. Final variants, totals, delivery, and payment remain platform controlled.</p></header><footer data-cd-policy-links></footer>`, css: `.haven-checkout{padding:48px}.haven-checkout h1{font-size:64px}`, layout: { columnMode: "summaryAside", sectionOrder: ["contact", "shipping", "delivery", "consent", "payment", "summary"], spacingTokenId: "space-room", surfaceTokenIds: ["ash", "walnut", "clay"] } } },
    notFound: { signature: "quiet off-plan recovery routing back to live furniture and search", source: route(`<main class="haven-lost"><span>404 / outside the plan</span><h1 class="haven-display">This room is not here.</h1><p>The requested page is not in the current storefront.</p><a class="haven-button" data-cd-route="collection">Browse furniture</a><a data-cd-route="search">Search the catalog</a></main>`, `${base}.haven-lost{display:grid;align-content:center;gap:1rem;min-height:75dvh;padding:clamp(2rem,8vw,8rem);background:linear-gradient(120deg,var(--ash),var(--clay));color:var(--walnut)}.haven-lost h1{font-size:clamp(4rem,10vw,9rem)}`) },
  },
  assets: HAVEN_ASSETS,
} satisfies RecipeConfig<"haven">;

export const HAVEN_RECIPE = compileRecipeConfig(HAVEN_RECIPE_CONFIG);
export const HAVEN_BUNDLE = HAVEN_RECIPE.bundle;
