import { describe, it, expect } from "vitest";
import { sanitizeStoreHtml, sanitizeDocHtml } from "./sanitize-html.server";
import type { BlockDocument } from "./types";

describe("sanitizeStoreHtml — security boundary", () => {
  it("strips <script>", () => {
    expect(sanitizeStoreHtml('<div>hi</div><script>alert(1)</script>')).not.toMatch(/<script/i);
  });
  it("strips inline event handlers", () => {
    const out = sanitizeStoreHtml('<img src="x.jpg" onerror="alert(1)"><div onclick="steal()">x</div>');
    expect(out).not.toMatch(/onerror/i);
    expect(out).not.toMatch(/onclick/i);
  });
  it("neutralizes javascript: URLs", () => {
    expect(sanitizeStoreHtml('<a href="javascript:alert(1)">x</a>')).not.toMatch(/javascript:/i);
  });
  it("drops iframe/object/embed/form/input", () => {
    const out = sanitizeStoreHtml('<iframe src="//e"></iframe><object></object><embed><form><input></form>');
    for (const tag of ["iframe", "object", "embed", "form", "input"]) expect(out).not.toMatch(new RegExp("<" + tag, "i"));
  });
  it("strips CSS @import and expression() from <style>", () => {
    const out = sanitizeStoreHtml('<style>@import url("//evil.css"); a{color:red} b{width:expression(alert(1))}</style>');
    expect(out).not.toMatch(/@import/i);
    expect(out).not.toMatch(/expression\s*\(/i);
  });
  it("@import strip never deletes across a tag boundary (no markup corruption)", () => {
    // A crafted @import with no terminating ; must not swallow later markup.
    const out = sanitizeStoreHtml('<style>@import "x"</style><p style="color:red">keep me</p>');
    expect(out).not.toMatch(/@import/i);
    expect(out).toContain("keep me"); // the following <p> survived intact
  });
  it("neutralizes the <style> rawtext-exit XSS (</style/ ... > differential)", () => {
    // htmlparser2 keeps "</style/><img onerror=…>" as inert CSS text, but a browser
    // ends the <style> at "</style/" and re-parses the <img> as live. The dangerous
    // solidus-terminated close tag must not survive.
    const out = sanitizeStoreHtml("<style></style/><img src=x onerror=alert(1)></style>");
    expect(out).not.toContain("</style/>");
    expect(out).not.toMatch(/<\/style[\s/]/);
    expect(out).toContain("&lt;/style");
  });
  it("does not rewrite document text outside <style> (no 'expression'/'@import' mangling)", () => {
    const out = sanitizeStoreHtml("<h1>freedom of expression (and more)</h1>");
    expect(out).toContain("expression (and more)");
  });
  it("drops HTML comments (no provenance leak)", () => {
    expect(sanitizeStoreHtml("<div>x</div><!-- generated by some tool -->")).not.toContain("<!--");
  });
});

describe("sanitizeStoreHtml — design is preserved", () => {
  it("keeps gradients + inline styles + big type", () => {
    const html = '<section style="background:linear-gradient(135deg,#7c3aed,#0b0b0f);padding:120px"><h1 style="font-size:5rem">Bold</h1></section>';
    const out = sanitizeStoreHtml(html);
    expect(out).toContain("linear-gradient");
    expect(out).toContain("font-size:5rem");
    expect(out).toMatch(/<h1/);
  });
  it("keeps a <style> block with real CSS (hover/media/keyframes)", () => {
    const html = "<style>.hero{color:#fff}.hero:hover{opacity:.8}@media(max-width:700px){.hero{padding:20px}}</style><div class=\"hero\">x</div>";
    const out = sanitizeStoreHtml(html);
    expect(out).toContain("<style>");
    expect(out).toContain(":hover");
    expect(out).toContain("@media");
  });
  it("keeps inline SVG shapes (image-free design)", () => {
    const out = sanitizeStoreHtml('<svg viewBox="0 0 10 10"><path d="M0 0h10v10z" fill="#7c3aed"/></svg>');
    expect(out).toMatch(/<svg/);
    expect(out).toMatch(/<path/);
  });
  it("marks external links safe (noopener) but keeps internal links plain", () => {
    expect(sanitizeStoreHtml('<a href="https://x.com">e</a>')).toMatch(/rel="[^"]*noopener/);
    expect(sanitizeStoreHtml('<a href="/storefront/cart">c</a>')).toContain('href="/storefront/cart"');
  });
});

describe("sanitizeDocHtml — document persistence boundary", () => {
  const doc = (html: string): BlockDocument => ({
    kind: "singleton", pageKey: "home",
    blocks: [
      { id: "h", type: "rawHtml", layout: { x: 0, y: 0, w: 12, h: 12 }, props: { html } },
      { id: "b", type: "button", layout: { x: 0, y: 12, w: 3, h: 1 }, props: { label: "Shop", href: "/storefront" } },
    ],
  });
  it("sanitizes a rawHtml block and leaves sibling blocks untouched", () => {
    const clean = sanitizeDocHtml(doc("<h1>ok</h1><script>bad()</script>"));
    expect((clean.blocks[0].props as { html: string }).html).not.toMatch(/<script/i);
    expect((clean.blocks[0].props as { html: string }).html).toContain("<h1>ok</h1>");
    expect(clean.blocks[1].props).toEqual({ label: "Shop", href: "/storefront" });
  });
  it("returns the same doc when it has no rawHtml block (cheap no-op)", () => {
    const plain: BlockDocument = { kind: "singleton", pageKey: "home", blocks: [{ id: "b", type: "button", layout: { x: 0, y: 0, w: 3, h: 1 }, props: {} }] };
    expect(sanitizeDocHtml(plain)).toBe(plain);
  });
});
