import { defineRecipe, prependRecipeLandmark, type RecipeConfig } from "../factory";
import { COMMONS_INDEX_ASSETS } from "./assets";

const shell = {
  html: `<header class="commons-shell"><a class="commons-brand" data-cd-route="home"><span class="niche-icon niche-icon--commons" aria-hidden="true">&#8634;</span><span data-cd-text="store.name"></span><b>The Commons Index</b></a><nav class="index-nav"><a data-cd-route="collection">Materials</a><a data-cd-route="search">Index search</a><a data-cd-route="account">Member account</a><a data-cd-route="cart">Basket <span data-cd-text="cart.count"></span></a></nav><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="forest acid paper"></aside></header><footer class="commons-footer"><span data-cd-text="store.name"></span><nav data-cd-policy-links></nav></footer>`,
  css: `.commons-brand { color:var(--forest); font-family:var(--font-display); font-size:1.6rem; text-decoration:none } .commons-brand b { display:block; font-family:var(--font-body); font-size:.7rem; text-transform:uppercase } .index-nav { display:flex; gap:1.5rem } .index-nav a { color:var(--forest); font-family:var(--font-body) } .commons-footer span { font-family:var(--font-display); font-weight:700 } @media(max-width:720px){.index-nav{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.index-nav a{border-bottom:1px solid var(--line);padding:.5rem 0}}`,
  requiredData: [], requiredCapabilities: [],
};

const home = {
  html: `<main class="commons-home"><section class="atlas-intro"><aside class="cycle-key"><h2>Material cycle</h2><ol><li>Source</li><li>Make</li><li>Use</li><li>Return</li></ol></aside><figure class="ledger-hero"><img data-cd-asset="hero" alt="Goods and materials documented by the cooperative"><figcaption><h1>Useful things, fully accounted for.</h1><p class="durable-copy">A cooperative index of materials, makers, live availability, and what happens after use.</p><a data-cd-route="collection">Open the living catalog</a></figcaption></figure></section><section class="records" data-cd-repeat="featured.products"><article data-cd-key="product.id"><small>Open record</small><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Read provenance</a><aside data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="panel" data-cd-theme-tokens="forest acid paper"></aside></article></section><section id="loop-record" class="loop-record" data-cd-state-id="loop-open" data-cd-state-type="boolean" data-cd-state-initial="false" data-cd-bind-state="loop-open" data-cd-bind-property="expanded"><h2>Refill, return, repeat.</h2><button value="toggle" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="loop-record">Trace the refill loop</button><dl><dt>Container</dt><dd>Returned to the merchant</dd><dt>Cleaning</dt><dd>Recorded by the cooperative</dd><dt>Next use</dt><dd>Reintroduced to live stock</dd></dl></section><button data-cd-on="click" data-cd-action="scroll.to" data-cd-target="loop-record">Go to refill record</button></main>`,
  css: `.atlas-intro { display:grid; grid-template-columns:16rem 1fr; min-height:42rem } .cycle-key { align-self:start;border-right:1px solid var(--line);padding:2rem;position:sticky;top:1rem } .cycle-key ol { border-left:1px dashed var(--forest); display:grid; gap:3rem; padding:2rem } .ledger-hero img { height:34rem; object-fit:cover; width:100% } .ledger-hero h1 { font-family:var(--font-display); font-size:clamp(3.7rem,8vw,8rem); line-height:.86; max-width:9ch } .records img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .records h2 { font-family:var(--font-display) } .loop-record { scroll-margin-top:2rem } .loop-record h2 { font-family:var(--font-display); font-size:clamp(3rem,6vw,6rem) } .loop-record dl { display:grid; grid-template-columns:1fr 2fr; opacity:.55 } .loop-record[aria-expanded="true"] dl { opacity:1; border-left:4px solid var(--acid) } @media(max-width:760px){ .atlas-intro { grid-template-columns:1fr } .cycle-key { border-right:0;position:static } } @media(prefers-reduced-motion:reduce){.cycle-key{position:static}}`,
  requiredData: [], requiredCapabilities: [],
};

const collection = {
  html: `<main class="cooperative-directory"><header class="directory-head"><small>Cooperative directory</small><h1 data-cd-text="collection.title"></h1><p class="durable-copy" data-cd-text="collection.description"></p><img data-cd-src="collection.image" data-cd-alt="collection.title"></header><nav class="evidence-filters" aria-label="Evidence filters"><button value="refillable" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Refillable</button><button value="repairable" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Repairable</button><button value="documented" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Documentation linked</button><button value="relevance" data-cd-on="click" data-cd-action="collection.sort">Evidence order</button></nav><section class="record-table" data-cd-repeat="collection.products"><article data-cd-key="product.id"><span>Material record</span><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Inspect record</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline" data-cd-theme-tokens="forest acid paper"></div></article></section><p class="directory-empty">No records match this evidence filter. Return to all materials to continue.</p></main>`,
  css: `.directory-head { display:grid; grid-template-columns:1.2fr .8fr; border-bottom:1px solid var(--forest) } .directory-head h1 { font-family:var(--font-display); font-size:clamp(4rem,9vw,8rem); line-height:.84 } .directory-head img { height:22rem; object-fit:cover; width:100% } .evidence-filters { display:flex; gap:.4rem; overflow:auto; padding:1rem } .evidence-filters button { background:var(--paper); border:1px solid var(--line); padding:.8rem } .record-table img { aspect-ratio:1 / 1; object-fit:cover; width:100% } .record-table h2 { font-family:var(--font-display) } .directory-empty { border-left:4px solid var(--acid); padding:2rem } @media(max-width:760px){ .directory-head { grid-template-columns:1fr } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "collection" as const,
};

const product = {
  html: `<main class="provenance-record"><section id="provenance-gallery" class="record-gallery"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><div data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"></figure></div></section><article class="record-copy"><small>Product provenance</small><h1 data-cd-text="product.title"></h1><p data-cd-money="product.price"></p><b data-cd-text="product.availability"></b><p class="durable-copy" data-cd-text="product.description"></p><p>Unavailable records keep their provenance visible while trusted purchase controls prevent ordering.</p><dl><dt>Material</dt><dd>Merchant documented</dd><dt>Maker</dt><dd>Source record attached</dd><dt>After use</dt><dd>Repair, refill, or recycle</dd></dl><div class="edition-index" data-cd-repeat="product.variants"><span data-cd-key="variant.id" data-cd-text="variant.title"></span></div><div id="edition-picker" data-cd-slot="variantPicker" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="forest acid paper"></div><div data-cd-slot="addToCart" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="forest acid paper"></div></article><section class="related-records" data-cd-repeat="related.products"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><a data-cd-route="product" data-cd-param-handle="product.handle">Next record</a></article></section></main>`,
  css: `.record-gallery img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .record-gallery button { background:transparent; border:1px solid var(--line); padding:.2rem } .record-copy h1 { font-family:var(--font-display); font-size:clamp(3.5rem,7vw,7rem); line-height:.85 } .record-copy dl { display:grid; grid-template-columns:1fr 2fr } .edition-index span { background:transparent; border:1px solid var(--line); display:inline-block; padding:.75rem } .related-records h2 { font-family:var(--font-display) }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "product" as const,
};

const search = {
  html: `<main class="index-search"><header><small>Maker and material index</small><h1>Search every recorded field.</h1><p data-cd-text="search.query"></p></header><div class="index-query" role="search"><span>Index query</span><input aria-label="Index query" type="search" name="q" value="" placeholder="Material, maker, or proof" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Search records</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear index</button></div><ol class="search-ledger" data-cd-repeat="search.results"><li data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Open evidence</a></li></ol><p class="directory-empty">No material or maker records found. Try a broader field.</p></main>`,
  css: `.index-search h1 { font-family:var(--font-display); font-size:clamp(3.5rem,8vw,7rem); max-width:10ch } .index-query { display:flex; gap:.5rem } .index-query input, .index-query button { background:var(--acid); border:1px solid var(--forest); padding:.8rem } .search-ledger { list-style:none; padding:0 } .search-ledger img { height:8rem; object-fit:cover; width:8rem } .search-ledger h2 { font-family:var(--font-display) }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "search" as const,
};

const cart = {
  html: `<main class="shared-basket"><header><small>Shared purchase ledger</small><h1>Basket records</h1><p><span data-cd-text="cart.count"></span> active lines</p></header><section class="basket-lines" data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><p data-cd-text="cartLine.quantity"></p><p data-cd-money="cartLine.unitPrice"></p><p data-cd-money="cartLine.total"></p><div data-cd-slot="cartLineControls" data-cd-host-size="inline" data-cd-theme-tokens="forest acid paper"></div></article></section><p class="directory-empty">The shared basket is empty. Add a documented object from the directory.</p><aside data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="forest acid paper"></aside></main>`,
  css: `.shared-basket h1 { font-family:var(--font-display); font-size:clamp(3.5rem,8vw,7rem) } .basket-lines h2 { font-family:var(--font-display) } .basket-lines p { font-family:var(--font-body) } .directory-empty { border-left:4px solid var(--acid); padding:2rem }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "cart" as const,
};

const checkout = {
  html: `<header class="ledger-checkout"><small>Cooperative checkout</small><h1 data-cd-text="store.name"></h1><p>The order summary leads, followed by trusted contact, delivery, consent, and payment sections.</p></header><aside class="claim-note"><b>Claims remain attached</b><p>Material records travel with the order confirmation.</p></aside><footer data-cd-policy-links></footer>`,
  css: `.ledger-checkout { padding:48px; background-color:var(--paper); color:var(--forest) } .ledger-checkout h1 { font-family:var(--font-display); font-size:54px; line-height:.9 } .claim-note { margin:24px 48px; padding:18px; border-width:1px; border-style:dashed; border-color:var(--forest) }`,
  layout: { columnMode: "summaryFirst" as const, sectionOrder: ["summary", "contact", "shipping", "delivery", "consent", "payment"], spacingTokenId: "space-ledger", surfaceTokenIds: ["paper", "forest", "acid"] },
} satisfies RecipeConfig<"commons-index">["surfaces"]["checkout"]["source"];

const config = {
  templateId: "commons-index", templateVersion: 1,
  concept: { name: "Commons Index", rationale: "A cooperative ledger makes sourcing and circular use part of browsing.", noveltySignature: ["civic atlas rail", "provenance records", "refill loop trace"] },
  designSystem: { displayFontId: "fraunces", bodyFontId: "atkinson-hyperlegible", tokens: { paper: "#f1efe3", forest: "#17352a", acid: "#d9ff3f", signal: "#f0522d", line: "#8f9883" }, breakpoints: { mobile: 760, wide: 1160 }, iconStyle: "civic index marks and material provenance stamps", motionStyle: "indexed ledger expansion with deliberate refill tracing", globalCss: `.durable-copy { overflow-wrap: anywhere }` },
  archetype: { composition: "cooperative-directory", hero: "impact-ledger-intro", scroll: "indexed-ledger", cards: "provenance-records", iconography: ["civic index marks", "material provenance stamps"] },
  surfaces: {
    shell: { signature: "cooperative masthead with material index and shared basket island", source: shell },
    home: { signature: "civic atlas rail joined to an impact-ledger hero and refill trace", source: home },
    collection: { signature: "evidence filters feeding a provenance record directory", source: collection },
    product: { signature: "documented product record with material lifecycle and edition controls", source: product },
    search: { signature: "maker and material query desk rendered as a ranked civic index", source: search },
    cart: { signature: "shared purchase ledger with authoritative line and total islands", source: prependRecipeLandmark(cart, `<section class="ledger-key"><small>Shared order record</small></section>`) },
    checkout: { signature: "summary-first cooperative checkout framed by claim continuity", source: checkout },
  }, assets: COMMONS_INDEX_ASSETS,
} satisfies RecipeConfig<"commons-index">;

export const COMMONS_INDEX_RECIPE = defineRecipe(config);

export const COMMONS_INDEX_BUNDLE = COMMONS_INDEX_RECIPE.bundle;
