import type { CSSProperties } from "react";
import {
  Archive,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Ban,
  Bell,
  BellOff,
  Bot,
  Box,
  Bug,
  AlignLeft,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Check,
  Clock,
  CloudRain,
  CloudSun,
  Coins,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Gauge,
  Globe,
  Heart,
  House,
  Image,
  LayoutGrid,
  Layers,
  LineChart,
  Lock,
  LogOut,
  Megaphone,
  MessageCircle,
  MessageSquareMore,
  Monitor,
  Moon,
  MoreHorizontal,
  MousePointer2,
  Paperclip,
  Pause,
  Pencil,
  PenLine,
  Play,
  Plus,
  Printer,
  Radar,
  Rocket,
  RotateCcw,
  LocateFixed,
  Mail,
  MapPin,
  Scissors,
  Search,
  Settings,
  Snowflake,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Store,
  Sun,
  Tag,
  Target,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  User,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface CDIconProps {
  name: string;
  size?: number;
  strokeWidth?: number;
  style?: CSSProperties;
  className?: string;
}

// name -> Lucide component. Names are stable so the 14 call sites never change.
export const CD_ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  bot: Bot,
  gauge: Gauge,
  home: House,
  bell: Bell,
  megaphone: Megaphone,
  sparkle: Sparkles,
  chart: LineChart,
  box: Box,
  clock: Clock,
  rain: CloudRain,
  download: Download,
  gear: Settings,
  bag: ShoppingBag,
  heart: Heart,
  scan: Radar,
  pause: Pause,
  reduce: ArrowDown,
  globe: Globe,
  swap: ArrowLeftRight,
  doc: FileText,
  snooze: BellOff,
  check: Check,
  x: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  search: Search,
  bolt: Zap,
  undo: Undo2,
  shield: ShieldCheck,
  sun: Sun,
  moon: Moon,
  play: Play,
  plus: Plus,
  rocket: Rocket,
  arrowRight: ArrowRight,
  rotate: RotateCcw,
  arrowUpRight: ArrowUpRight,
  warn: TriangleAlert,
  assist: MessageSquareMore,
  ban: Ban,
  scissors: Scissors,
  trendingUp: TrendingUp,
  rotateCcw: RotateCcw,
  tag: Tag,
  more: MoreHorizontal,
  bug: Bug,
  target: Target,
  lock: Lock,
  eye: Eye,
  list: AlignLeft,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  user: User,
  truck: Truck,
  card: CreditCard,
  store: Store,
  coin: Coins,
  layers: Layers,
  image: Image,
  cursor: MousePointer2,
  paperclip: Paperclip,
  pencil: Pencil,
  comment: MessageCircle,
  sliders: SlidersHorizontal,
  pen: PenLine,
  logout: LogOut,
  arrowUp: ArrowUp,
  monitor: Monitor,
  phone: Smartphone,
  grid: LayoutGrid,
  external: ExternalLink,
  cloudSun: CloudSun,
  snowflake: Snowflake,
  mapPin: MapPin,
  locate: LocateFixed,
  printer: Printer,
  arrowDown: ArrowDown,
  mail: Mail,
};

export function CDIcon({
  name,
  size = 20,
  strokeWidth = 1.7,
  style,
  className,
}: CDIconProps): JSX.Element {
  const Icon = CD_ICONS[name] ?? Radar;
  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      style={style}
      className={className}
      aria-hidden="true"
    />
  );
}

export const CD_ACTION_ICON: Record<string, string> = {
  pause_campaign: "pause",
  reduce_campaign_budget: "reduce",
  reallocate_budget: "swap",
  reallocate_spend_sku: "trendingUp",
  exclude_geo: "globe",
  reallocate_inventory: "swap",
  create_po_draft: "doc",
  snooze_alert: "snooze",
  discontinue: "ban",
  discontinue_sku: "archive",
  adjust_price: "tag",
  cut_ads: "scissors",
  reallocate_to_winner: "trendingUp",
  fix_returns: "rotateCcw",
  review_pricing: "tag",
};
