import { defineRecipe, type RecipeConfig } from "../factory";
import { COMPANION_FIELD_GUIDE_ASSETS } from "./assets";

const shell = {
  html: `<header class="guide-shell"><a class="guide-brand" data-cd-route="home"><small>Companion supply</small><span data-cd-text="store.name"></span><b>Field Guide</b></a><nav class="chapter-nav"><a data-cd-route="collection">Care chapters</a><a data-cd-route="search">Guide search</a><a data-cd-route="account">Pet profile</a></nav><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="forest orange paper"></aside></header><footer class="guide-footer"><span data-cd-text="store.name"></span><nav data-cd-policy-links></nav></footer>`,
  css: `.guide-brand { color:var(--forest); font-family:var(--font-display); font-size:1.5rem; text-decoration:none } .guide-brand small, .guide-brand b { display:block; font-family:var(--font-body); font-size:.65rem; letter-spacing:.1em; text-transform:uppercase } .chapter-nav { display:flex; gap:1.4rem } .chapter-nav a { color:var(--forest); font-family:var(--font-body); text-decoration:none } .guide-footer span { font-family:var(--font-display) }`,
  requiredData: [], requiredCapabilities: [],
};

const home = {
  html: `<main class="field-home"><section class="profile-hero"><aside id="companion-profile" class="profile-rail" data-cd-state-id="companion" data-cd-state-type="enum" data-cd-state-initial="all" data-cd-state-values="all dog cat senior" data-cd-bind-state="companion" data-cd-bind-property="classToken"><h2>Build a companion profile</h2><button data-cd-on="click" data-cd-action="state.set" data-cd-state="companion">All companions</button><button data-cd-on="click" data-cd-action="state.set" data-cd-state="companion">Dog</button><button data-cd-on="click" data-cd-action="state.set" data-cd-state="companion">Cat</button><button data-cd-on="click" data-cd-action="state.set" data-cd-state="companion">Senior</button></aside><div class="profile-copy"><small>Daily care, considered</small><h1>Know their world. Care for it.</h1><p class="guide-copy">Food, support, and everyday tools organized around species, life stage, and the way a companion lives.</p><a data-cd-route="collection">Open their guide</a></div><figure class="companion-portrait"><img data-cd-asset="hero" alt="Companion outdoors in soft natural light"><figcaption>Current care chapter: daily vitality</figcaption></figure></section><section id="care-chapters" class="care-chapters"><h2>Portraits of everyday care.</h2><div class="chapter-shelf" data-cd-repeat="featured.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h3 data-cd-text="product.title"></h3><p data-cd-text="product.availability"></p><p data-cd-money="product.price"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Read care notes</a></article></div></section><button data-cd-on="click" data-cd-action="scroll.to" data-cd-target="care-chapters">Browse care chapters</button><aside data-cd-slot="quickViewCommerce" data-cd-host-size="panel" data-cd-theme-tokens="forest orange paper"></aside></main>`,
  css: `.profile-hero { display:grid; grid-template-columns:15rem minmax(18rem,.8fr) minmax(24rem,1.2fr); min-height:43rem } .profile-rail { background:var(--forest); color:var(--paper); padding:2rem } .profile-rail h2 { font-family:var(--font-display) } .profile-rail button { background:transparent; border:0; border-bottom:1px solid var(--mint); color:var(--paper); padding:1rem 0; text-align:left; width:100% } .profile-copy { align-content:center; display:grid; padding:clamp(2rem,5vw,5rem) } .profile-copy h1 { font-family:var(--font-display); font-size:clamp(3.8rem,7vw,7rem); line-height:.84 } .companion-portrait img { height:40rem; object-fit:cover; width:100% } .companion-portrait figcaption { background:var(--orange); color:var(--paper); padding:1rem } .care-chapters h2 { font-family:var(--font-display); font-size:clamp(3rem,6vw,6rem) } .chapter-shelf { display:grid; grid-template-columns:1.15fr .85fr .85fr; gap:1rem } .chapter-shelf img { aspect-ratio:3 / 4; object-fit:cover; width:100% } .chapter-shelf h3 { font-family:var(--font-display); font-size:1.8rem } @media(max-width:900px){ .profile-hero { grid-template-columns:1fr } .profile-rail { display:flex; overflow:auto } .profile-rail button { min-width:8rem } .companion-portrait img { height:28rem } .chapter-shelf { display:flex; overflow:auto } .chapter-shelf article { min-width:80vw } }`,
  requiredData: [], requiredCapabilities: [],
};

const collection = {
  html: `<main class="working-shelf"><header class="chapter-intro"><div><small>Care chapter</small><h1 data-cd-text="collection.title"></h1><p class="guide-copy" data-cd-text="collection.description"></p></div><img data-cd-src="collection.image" data-cd-alt="collection.title"></header><aside class="care-filters" aria-label="Companion care filters"><h2>Refine the guide</h2><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="species">Dog</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="species">Cat</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="life-stage">Senior</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="need">Sensitive care</button><button data-cd-on="click" data-cd-action="collection.sort">Field guide order</button></aside><section class="field-note-grid" data-cd-repeat="collection.products"><article data-cd-key="product.id"><small>Care field note</small><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">View care details</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline" data-cd-theme-tokens="forest orange paper"></div></article></section><p class="care-empty">No essentials match this care chapter. Clear a species or life-stage filter.</p></main>`,
  css: `.chapter-intro { display:grid; grid-template-columns:1fr .8fr; min-height:22rem } .chapter-intro h1 { font-family:var(--font-display); font-size:clamp(4rem,8vw,7rem); line-height:.84 } .chapter-intro img { height:22rem; object-fit:cover; width:100% } .care-filters { display:flex; gap:.5rem; overflow:auto; padding:1rem } .care-filters h2 { font-family:var(--font-display); min-width:max-content } .care-filters button { background:var(--paper); border:1px solid var(--forest); padding:.8rem 1rem } .field-note-grid img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .field-note-grid h2 { font-family:var(--font-display) } .care-empty { background:var(--mint); border-left:4px solid var(--forest); padding:2rem } @media(max-width:760px){ .chapter-intro { grid-template-columns:1fr } .chapter-intro img { height:15rem } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "collection" as const,
};

const product = {
  html: `<main class="care-record"><section id="care-gallery" class="care-gallery"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><div data-cd-repeat="product.images"><button data-cd-key="product.primaryImage" data-cd-on="click" data-cd-action="gallery.select" data-cd-target="care-gallery"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"></button></div></section><article id="care-facts" class="care-facts"><small>Companion field record</small><h1 data-cd-text="product.title"></h1><p data-cd-money="product.price"></p><b data-cd-text="product.availability"></b><p class="guide-copy" data-cd-text="product.description"></p><p>Currently unavailable care notes remain readable, while trusted commerce controls prevent an invalid addition.</p><button data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="care-facts">Serving and dosage</button><button data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="care-facts">Species and life stage</button><button data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="care-facts">Safety notes</button><div class="format-notes" data-cd-repeat="product.variants"><button data-cd-key="variant.id" data-cd-text="variant.title" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="format-picker"></button></div><div id="format-picker" data-cd-slot="variantPicker" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="forest orange paper"></div><div data-cd-slot="addToCart" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="forest orange paper"></div></article><section class="next-chapter" data-cd-repeat="related.products"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><a data-cd-route="product" data-cd-param-handle="product.handle">Next care note</a></article></section></main>`,
  css: `.care-gallery img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .care-gallery button { background:transparent; border:1px solid var(--forest); padding:.25rem } .care-facts h1 { font-family:var(--font-display); font-size:clamp(3.5rem,7vw,6.8rem); line-height:.86 } .care-facts p { max-width:44rem } .care-facts button { background:transparent; border:0; border-top:1px solid var(--forest); padding:1rem; text-align:left; width:100% } .format-notes button { border:1px solid var(--forest); width:auto } .next-chapter h2 { font-family:var(--font-display) }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "product" as const,
};

const search = {
  html: `<main class="guide-search"><header><small>Search the care guide</small><h1>Find a product, species, or need.</h1><p data-cd-text="search.query"></p></header><div class="guide-query" role="search"><button data-cd-on="input" data-cd-action="search.update">Update guide query</button><button data-cd-on="click" data-cd-action="search.submit">Search guide</button><button data-cd-on="click" data-cd-action="search.clear">Clear query</button></div><section class="chapter-results" data-cd-repeat="search.results"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Open field note</a></article></section><p class="care-empty">No matching care chapter. Try a species, need, or product name.</p></main>`,
  css: `.guide-search h1 { font-family:var(--font-display); font-size:clamp(3.4rem,7vw,6.8rem); max-width:12ch } .guide-query { display:flex; gap:.5rem } .guide-query button { background:var(--orange); border:1px solid var(--forest); color:var(--paper); padding:.8rem } .chapter-results { display:grid; grid-template-columns:repeat(3,1fr) } .chapter-results img { aspect-ratio:1 / 1; object-fit:cover; width:100% } .chapter-results h2 { font-family:var(--font-display) } @media(max-width:760px){ .chapter-results { grid-template-columns:1fr } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "search" as const,
};

const cart = {
  html: `<main class="field-bag"><header><small>Companion supply list</small><h1>Your field bag</h1><p><span data-cd-text="cart.count"></span> care essentials</p></header><section class="bag-lines" data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><p data-cd-text="cartLine.quantity"></p><p data-cd-money="cartLine.unitPrice"></p><p data-cd-money="cartLine.total"></p><div data-cd-slot="cartLineControls" data-cd-host-size="inline" data-cd-theme-tokens="forest orange paper"></div></article></section><p class="care-empty">Your field bag is empty. Open a care chapter to choose an essential.</p><aside data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="forest orange paper"></aside></main>`,
  css: `.field-bag h1 { font-family:var(--font-display); font-size:clamp(3.5rem,8vw,7rem) } .bag-lines h2 { font-family:var(--font-display) } .bag-lines p { font-family:var(--font-body) } .care-empty { background:var(--mint); border-left:4px solid var(--forest); padding:2rem }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "cart" as const,
};

const checkout = {
  html: `<header class="field-checkout"><small>Secure field bag checkout</small><h1 data-cd-text="store.name"></h1><p>Contact and delivery sit beside the trusted order summary, with care notes retained after purchase.</p></header><aside class="care-note"><b>Care information included</b><p>Serving, safety, and life-stage details remain with the order.</p></aside><footer data-cd-policy-links></footer>`,
  css: `.field-checkout { padding:48px; background-color:var(--paper); color:var(--forest) } .field-checkout h1 { font-family:var(--font-display); font-size:54px; line-height:.9 } .care-note { margin:24px 48px; padding:18px; background-color:var(--mint); border-width:1px; border-style:solid; border-color:var(--forest) }`,
  layout: { columnMode: "summaryAside" as const, sectionOrder: ["contact", "shipping", "delivery", "consent", "payment", "summary"], spacingTokenId: "space-guide", surfaceTokenIds: ["paper", "forest", "mint", "orange"] },
} satisfies RecipeConfig<"companion-field-guide">["surfaces"]["checkout"]["source"];

export const COMPANION_FIELD_GUIDE_RECIPE = defineRecipe({
  templateId: "companion-field-guide", templateVersion: 1,
  concept: { name: "Companion Field Guide", rationale: "A chaptered guide lets people shop from the care context they recognize.", noveltySignature: ["species chapter rail", "companion profile", "care field records"] },
  designSystem: { displayFontId: "roboto-slab", bodyFontId: "atkinson-hyperlegible", tokens: { paper: "#f3f1e8", ink: "#1d2b22", forest: "#234e3b", mint: "#c8dfcc", orange: "#df693e" }, breakpoints: { mobile: 760, wide: 1180 }, iconStyle: "species field marks and dosage fact symbols", motionStyle: "chapter changes and profile feedback with restrained portrait reveals", globalCss: `.guide-copy { overflow-wrap: anywhere }` },
  archetype: { composition: "field-guide", hero: "pet-profile-hero", scroll: "chaptered-guide", cards: "field-notes", iconography: ["species field marks", "dosage fact symbols"] },
  surfaces: {
    shell: { signature: "field-guide masthead linking care chapters, pet profile, and trusted bag", source: shell },
    home: { signature: "species profile rail beside companion portrait and chapter shelf", source: home },
    collection: { signature: "life-stage filters opening a working shelf of field notes", source: collection },
    product: { signature: "care portrait gallery paired with dosage, safety, and format facts", source: product },
    search: { signature: "care-guide query header above chapter-shaped product results", source: search },
    cart: { signature: "field bag supply list with trusted line controls and care summary", source: cart },
    checkout: { signature: "care-note frame beside summary-aside trusted checkout", source: checkout },
  }, assets: COMPANION_FIELD_GUIDE_ASSETS,
} satisfies RecipeConfig<"companion-field-guide">);

export const COMPANION_FIELD_GUIDE_BUNDLE = COMPANION_FIELD_GUIDE_RECIPE.bundle;
