import { defineRecipe, type RecipeConfig } from "../factory";
import { SOFT_CHEMISTRY_ASSETS } from "./assets";

const shell = {
  html: `<header class="chemistry-shell"><span class="niche-icon niche-icon--chemistry" aria-hidden="true">&#9675;</span><a class="chemistry-wordmark" data-cd-route="home"><span data-cd-text="store.name"></span><b>Soft Chemistry</b></a><nav class="formula-nav"><a data-cd-route="collection">Formulas</a><a data-cd-route="search">Ingredients</a><a data-cd-route="account">Account</a><a data-cd-route="cart">Routine <span data-cd-text="cart.count"></span></a></nav><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="milk ink yellow"></aside></header><footer class="chemistry-footer"><span data-cd-text="store.name"></span><nav data-cd-policy-links></nav></footer>`,
  css: `.chemistry-wordmark { color:var(--ink); font-family:var(--font-display); font-size:1.8rem; text-decoration:none } .chemistry-wordmark b { display:block; font-family:var(--font-body); font-size:.65rem; letter-spacing:.12em; text-transform:uppercase } .formula-nav { display:flex; gap:1.5rem } .formula-nav a { color:var(--ink); font-family:var(--font-body); font-size:.75rem; text-decoration:none; text-transform:uppercase } .chemistry-footer span { font-family:var(--font-display) } @media(max-width:720px){.formula-nav{max-width:100%;overflow-x:auto;padding:.5rem 0}.formula-nav a{min-width:max-content}}`,
  requiredData: [], requiredCapabilities: [],
};

const home = {
  html: `<main class="chemistry-home"><section class="formula-hero"><figure><img data-cd-asset="hero" alt="Soft Chemistry formulas in a luminous clinical studio"></figure><div class="formula-intro"><small>Barrier routine</small><h1>Skin, in its softer state.</h1><p class="clinical-copy">Ingredient-led formulas arranged into a calm sequence with live products, prices, and availability.</p><a data-cd-route="collection">Enter the formulation studio</a></div></section><section id="routine-sequence" class="routine-sequence"><header><h2>Assemble the routine</h2><p>Choose a place in the sequence, then open the matching live formula.</p></header><div class="routine-tabs"><button value="cleanse" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="routine-sequence">Cleanse</button><button value="treat" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="routine-sequence">Treat</button><button value="seal" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="routine-sequence">Seal</button></div><div class="formula-sheets" data-cd-repeat="featured.products"><article data-cd-key="product.id"><small>Formula sheet</small><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h3 data-cd-text="product.title"></h3><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Read dossier</a></article></div></section><section data-cd-repeat="featured.products"><aside data-cd-key="product.id" data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="panel" data-cd-theme-tokens="milk ink yellow"></aside></section><section class="concern-index"><h2>Begin with what skin needs.</h2><a data-cd-route="collection">Dryness</a><a data-cd-route="collection">Barrier</a><a data-cd-route="collection">Texture</a><a data-cd-route="collection">Scalp</a></section><button data-cd-on="click" data-cd-action="scroll.to" data-cd-target="routine-sequence">Return to routine</button></main>`,
  css: `.formula-hero { display:grid; grid-template-columns:1.15fr .85fr; min-height:42rem; background:var(--ink); color:var(--milk) } .formula-hero img { height:42rem; object-fit:cover; width:100% } .formula-intro { align-content:end; display:grid; padding:clamp(2rem,6vw,6rem); position:sticky;top:1rem } .formula-intro h1 { font-family:var(--font-display); font-size:clamp(4rem,9vw,8rem); line-height:.78; max-width:8ch } .routine-sequence { scroll-margin-top:2rem } .routine-sequence h2, .concern-index h2 { font-family:var(--font-display); font-size:clamp(3rem,6vw,6rem); line-height:.86 } .routine-sequence[data-cd-active-value] { border-top:5px solid var(--yellow) } .routine-tabs { display:flex; gap:.5rem } .routine-tabs button { background:transparent; border:1px solid var(--ink); padding:.8rem 1.4rem } .formula-sheets { display:grid; grid-template-columns:1fr 1.2fr .9fr; gap:1rem } .formula-sheets img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .formula-sheets h3 { font-family:var(--font-display); font-size:2rem } .concern-index { display:grid; grid-template-columns:2fr repeat(4,1fr) } .concern-index a { border-left:1px solid var(--ink); color:var(--ink); padding:2rem; text-decoration:none } @media(max-width:760px){ .formula-hero { grid-template-columns:1fr } .formula-hero img { height:26rem } .formula-intro { position:static } .formula-sheets { display:flex; overflow-x:auto } .formula-sheets article { min-width:78vw } .concern-index { grid-template-columns:1fr 1fr } } @media(prefers-reduced-motion:reduce){.formula-intro{position:static}}`,
  requiredData: [], requiredCapabilities: [],
};

const collection = {
  html: `<main class="formula-library"><header class="library-intro"><div><small>Clinical formula library</small><h1 data-cd-text="collection.title"></h1><p class="clinical-copy" data-cd-text="collection.description"></p></div><img data-cd-src="collection.image" data-cd-alt="collection.title"></header><nav class="concern-filters" aria-label="Skin concern filters"><button value="cleanse" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="category">Cleanse</button><button value="barrier" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Barrier</button><button value="fragrance-free" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Fragrance free</button><button value="relevance" data-cd-on="click" data-cd-action="collection.sort">Ritual order</button></nav><section class="dossier-grid" data-cd-repeat="collection.products"><article data-cd-key="product.id"><small>Ingredient dossier</small><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><p data-cd-text="product.availability"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Open formula</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline" data-cd-theme-tokens="milk ink yellow"></div></article></section><p class="formula-empty">No formulas match this concern. Clear the concern filter to see the full ritual.</p></main>`,
  css: `.library-intro { display:grid; grid-template-columns:1fr 1fr; min-height:23rem } .library-intro h1 { font-family:var(--font-display); font-size:clamp(4rem,8vw,7.5rem); line-height:.82 } .library-intro img { height:23rem; object-fit:cover; width:100% } .concern-filters { display:flex; gap:.5rem; overflow:auto; padding:1rem } .concern-filters button { background:var(--milk); border:1px solid var(--ink); padding:.8rem 1rem } .dossier-grid img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .dossier-grid h2 { font-family:var(--font-display); font-size:2rem } .formula-empty { background:var(--lilac); padding:2rem } @media(max-width:760px){ .library-intro { grid-template-columns:1fr } .library-intro img { height:15rem } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "collection" as const,
};

const product = {
  html: `<main class="formula-dossier"><section id="formula-gallery" class="formula-gallery"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><div data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"></figure></div></section><article id="ingredient-dossier" class="ingredient-copy" data-cd-state-id="ingredients-open" data-cd-state-type="boolean" data-cd-state-initial="false" data-cd-bind-state="ingredients-open" data-cd-bind-property="expanded"><small>Complete formula dossier</small><h1 data-cd-text="product.title"></h1><p data-cd-money="product.price"></p><b data-cd-text="product.availability"></b><p class="clinical-copy" data-cd-text="product.description"></p><p>Unavailable formulas retain their ingredient dossier and layering guidance while purchase controls remain disabled.</p><button value="ingredients" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="ingredient-dossier">Key ingredients</button><button value="layer" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="ingredient-dossier">How to layer</button><button value="standard" data-cd-on="click" data-cd-action="accordion.toggle" data-cd-target="ingredient-dossier">Formula standard</button><div class="format-list" data-cd-repeat="product.variants"><span data-cd-key="variant.id" data-cd-text="variant.title"></span></div><div id="format-picker" data-cd-slot="variantPicker" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="milk ink yellow"></div><div data-cd-slot="addToCart" data-cd-product="product.id" data-cd-host-size="block" data-cd-theme-tokens="milk ink yellow"></div></article><section class="routine-continuation" data-cd-repeat="related.products"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><a data-cd-route="product" data-cd-param-handle="product.handle">Continue routine</a></article></section></main>`,
  css: `.formula-gallery img { aspect-ratio:4 / 5; object-fit:cover; width:100% } .ingredient-copy h1 { font-family:var(--font-display); font-size:clamp(3.5rem,7vw,7rem); line-height:.82 } .ingredient-copy p { max-width:46rem } .ingredient-copy button { background:transparent; border:0; border-top:1px solid var(--ink); padding:1rem; text-align:left; width:100% } .ingredient-copy[aria-expanded="true"] { border-left:5px solid var(--yellow); padding-left:1rem } .format-list span { border:1px solid var(--ink); display:inline-block; padding:.75rem; width:auto } .routine-continuation h2 { font-family:var(--font-display) }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "product" as const,
};

const search = {
  html: `<main class="ingredient-search"><header><small>Formula and INCI search</small><h1>Search by formula, ingredient, or concern.</h1><p data-cd-text="search.query"></p></header><div class="search-controls" role="search"><input aria-label="Formula search" type="search" name="q" value="" placeholder="Formula, ingredient, or concern" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Search formulas</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear query</button></div><section class="search-dossiers" data-cd-repeat="search.results"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title"><h2 data-cd-text="product.title"></h2><p data-cd-money="product.price"></p><a data-cd-route="product" data-cd-param-handle="product.handle">Read formula</a></article></section><p class="formula-empty">No formula or ingredient result. Try a broader concern.</p></main>`,
  css: `.ingredient-search h1 { font-family:var(--font-display); font-size:clamp(3.2rem,7vw,6.5rem); max-width:13ch } .search-controls { display:flex; gap:.5rem } .search-controls input, .search-controls button { background:var(--yellow); border:1px solid var(--ink); padding:.8rem } .search-dossiers { display:grid; grid-template-columns:repeat(2,1fr) } .search-dossiers img { aspect-ratio:1 / 1; object-fit:cover; width:100% } .search-dossiers h2 { font-family:var(--font-display) } @media(max-width:760px){ .search-dossiers { grid-template-columns:1fr } }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "search" as const,
};

const cart = {
  html: `<main class="ritual-cart"><header><small>Current ritual</small><h1>Your formula sequence</h1><p><span data-cd-text="cart.count"></span> formulas</p></header><ol class="ritual-lines" data-cd-repeat="cart.lines"><li data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><p data-cd-text="cartLine.quantity"></p><p data-cd-money="cartLine.unitPrice"></p><p data-cd-money="cartLine.total"></p><div data-cd-slot="cartLineControls" data-cd-host-size="inline" data-cd-theme-tokens="milk ink yellow"></div></li></ol><p class="formula-empty">Your routine is empty. Start with a concern or a place in the sequence.</p><aside data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="milk ink yellow"></aside></main>`,
  css: `.ritual-cart h1 { font-family:var(--font-display); font-size:clamp(3.5rem,8vw,7rem); line-height:.85 } .ritual-lines h2 { font-family:var(--font-display) } .ritual-lines p { font-family:var(--font-body) } .formula-empty { background:var(--lilac); padding:2rem }`,
  requiredData: [], requiredCapabilities: [], rootScopeKind: "cart" as const,
};

const checkout = {
  html: `<header class="soft-checkout"><small>Secure formula checkout</small><h1 data-cd-text="store.name"></h1><p>A quiet single-column frame keeps contact, delivery, consent, payment, and summary in one readable sequence.</p></header><aside class="formula-note"><b>Formula details stay visible</b><p>Warnings and merchant-authored usage notes remain attached to the order.</p></aside><footer data-cd-policy-links></footer>`,
  css: `.soft-checkout { padding:48px; background-color:var(--milk); color:var(--ink) } .soft-checkout h1 { font-family:var(--font-display); font-size:54px; line-height:.9 } .formula-note { margin:24px 48px; padding:18px; background-color:var(--lilac); border-width:1px; border-style:solid; border-color:var(--ink) }`,
  layout: { columnMode: "single" as const, sectionOrder: ["contact", "shipping", "delivery", "consent", "payment", "summary"], spacingTokenId: "space-clinical", surfaceTokenIds: ["milk", "ink", "lilac", "yellow"] },
} satisfies RecipeConfig<"soft-chemistry">["surfaces"]["checkout"]["source"];

export const SOFT_CHEMISTRY_RECIPE = defineRecipe({
  templateId: "soft-chemistry", templateVersion: 1,
  concept: { name: "Soft Chemistry", rationale: "A clinical editorial sequence makes formula choice transparent without making the store feel sterile.", noveltySignature: ["routine sheets", "ingredient dossier", "concern index"] },
  designSystem: { displayFontId: "source-serif-4", bodyFontId: "inter", tokens: { milk: "#f4f0eb", ink: "#231e27", lilac: "#c8b6e9", blue: "#a7d7e7", yellow: "#ecff5b" }, breakpoints: { mobile: 760, wide: 1180 }, iconStyle: "fine ingredient diagrams and quiet clinical symbols", motionStyle: "soft reveals motivated by routine sequence and dossier disclosure", globalCss: `.clinical-copy { overflow-wrap: anywhere }` },
  archetype: { composition: "clinical-editorial", hero: "ingredient-routine-hero", scroll: "soft-reveal", cards: "ingredient-dossiers", iconography: ["fine ingredient diagrams", "quiet clinical symbols"] },
  surfaces: {
    shell: { signature: "quiet formula masthead with ingredient navigation and trusted bag", source: shell },
    home: { signature: "luminous formula hero flowing into layered routine sheets and concerns", source: home },
    collection: { signature: "clinical concern controls above an ingredient dossier library", source: collection },
    product: { signature: "formula gallery paired with expandable ingredient and layering dossier", source: product },
    search: { signature: "formula and ingredient query field above paired editorial dossiers", source: search },
    cart: { signature: "ordered ritual sequence with trusted formula line controls and summary", source: cart },
    checkout: { signature: "single-column clinical checkout with formula continuity note", source: checkout },
  }, assets: SOFT_CHEMISTRY_ASSETS,
} satisfies RecipeConfig<"soft-chemistry">);

export const SOFT_CHEMISTRY_BUNDLE = SOFT_CHEMISTRY_RECIPE.bundle;
