// app/lib/seo/override.ts
// Pure override layering. A merchant's stored meta_title/meta_description win over
// the engine-generated draft. render.server derives og:title/og:description from
// draft.title/description, so overriding those keeps the OG tags consistent for
// free. JSON-LD (schema.org name/description) stays engine-generated by design:
// only the human-facing SERP title/description are merchant-editable in v1.
// The override argument is structural (metaTitle/metaDescription) so this module
// stays pure and needs no import from seo-store.server.
import type { SeoDraft } from "./types";

export function applyOverride(
  draft: SeoDraft,
  override: { metaTitle: string | null; metaDescription: string | null } | null,
): SeoDraft {
  if (!override) return draft;
  const title = override.metaTitle?.trim();
  const description = override.metaDescription?.trim();
  if (!title && !description) return draft;
  return {
    ...draft,
    title: title || draft.title,
    description: description || draft.description,
  };
}
