import { compileRecipeConfig, type RecipeConfig } from "../factory";
import { motionAttributes } from "../library/motion";
import { FORGE_ASSETS } from "./assets";

const source = (html: string, css: string, rootScopeKind?: "product" | "search" | "cart") => ({
  html,
  css: `${css}.forge-copy{overflow-wrap:anywhere}`,
  requiredData: [],
  requiredCapabilities: [],
  ...(rootScopeKind ? { rootScopeKind } : {}),
});

const productCard = `<article class="forge-card forge-copy" data-cd-key="product.id"><a data-cd-route="product" data-cd-param-handle="product.handle"><figure><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="720" height="720"><span data-cd-text="product.availability"></span></figure><div class="forge-card-copy"><small>Live inventory / merchant record</small><h3 data-cd-text="product.title"></h3><p data-cd-text="product.description"></p><dl><div><dt>Price</dt><dd data-cd-money="product.price"></dd></div><div><dt>Status</dt><dd data-cd-text="product.availability"></dd></div></dl></div></a></article>`;
const collectionCard = `<article class="forge-project-card forge-copy" data-cd-key="collection.id"><a data-cd-route="collection" data-cd-param-handle="collection.handle"><span class="forge-label">Live merchant collection</span><h3 data-cd-text="collection.title"></h3><p data-cd-text="collection.description"></p><b><span data-cd-text="collection.productCount"></span> products</b></a></article>`;
const productCardsCss = `.forge-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--line)}.forge-card{min-width:0;background:var(--parchment)}.forge-card a{display:block;color:inherit;text-decoration:none}.forge-card figure{position:relative;margin:0;aspect-ratio:4/3;overflow:hidden;background:var(--steel)}.forge-card img{width:100%;height:100%;object-fit:cover}.forge-card figure span{position:absolute;top:.75rem;left:.75rem;padding:.35rem .5rem;background:var(--steel);color:var(--parchment);font:600 .65rem var(--font-body);text-transform:uppercase}.forge-card-copy{padding:1rem}.forge-card h3{margin:.35rem 0;font:700 clamp(1.5rem,2.6vw,2.5rem)/.95 var(--font-display);text-transform:uppercase}.forge-card p{min-height:3.2rem;font-size:.78rem}.forge-card dl{display:grid;grid-template-columns:1fr 1fr;gap:.5rem;margin:.75rem 0 0}.forge-card dt{font-size:.58rem;text-transform:uppercase;color:var(--steel)}.forge-card dd{margin:0;color:var(--orange);font-weight:700}.forge-card b{color:var(--orange)}.forge-project-card{background:var(--parchment);border:1px solid var(--steel)}.forge-project-card a{display:grid;gap:.8rem;min-height:100%;padding:clamp(1.2rem,3vw,2.5rem);color:inherit;text-decoration:none}.forge-project-card h3{margin:0;font:700 clamp(2rem,4vw,4.5rem)/.85 var(--font-display);text-transform:uppercase}.forge-project-card p{font-size:.8rem}@media(max-width:760px){.forge-grid{grid-template-columns:1fr}}`;

export const FORGE_RECIPE_CONFIG = {
  templateId: "forge",
  templateVersion: 2,
  concept: {
    name: "Forge",
    rationale: "A jobsite blueprint that lets working catalogs present merchant-authored compatibility evidence before protected purchase actions.",
    noveltySignature: ["blueprint-coordinate-grid", "exploded-tool-records", "verified-line-item-loadout"],
  },
  designSystem: {
    displayFontId: "oswald",
    bodyFontId: "dm-mono",
    tokens: {
      steel: "#24313a",
      "steel-dark": "#172027",
      orange: "#96390f",
      parchment: "#efe4ce",
      ink: "#182127",
      line: "#89949a",
      "drawing-gap": "20px",
    },
    breakpoints: { compact: 760, wide: 1320 },
    iconStyle: "numbered drawing callouts and dimension ticks",
    motionStyle: "measured blueprint reveals with reduced-motion static sections",
    globalCss: `.forge-label{font:700 .68rem var(--font-body);letter-spacing:.12em;text-transform:uppercase}.forge-search-head>a{color:var(--parchment)}@media(prefers-reduced-motion:reduce){.forge-motion{animation:none!important;transform:none!important;transition:none!important}}`,
  },
  archetype: {
    composition: "jobsite-blueprint",
    hero: "exploded-tool-hero",
    scroll: "blueprint-flow",
    cards: "tool-diagrams",
    iconography: ["numbered component circles", "dimension lines"],
  },
  surfaces: {
    shell: {
      signature: "steel drawing-title block with project navigation and protected loadout drawer",
      source: source(
        `<header class="forge-shell"><a class="forge-mark" data-cd-route="home"><span aria-hidden="true">F//</span><b data-cd-text="store.name">Forge</b></a><nav aria-label="Primary navigation"><a data-cd-route="collections">Projects</a><a data-cd-route="collection">Tools</a><a data-cd-route="story">Field notes</a><a data-cd-route="search">Search</a><a data-cd-route="cart">Loadout <span data-cd-text="cart.count"></span></a></nav><a class="forge-account" data-cd-route="account">Account</a></header><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="steel steel-dark orange parchment"></aside><footer class="forge-footer"><span data-cd-text="store.name"></span><nav data-cd-policy-links></nav></footer>`,
        `.forge-shell{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:1rem;padding:.8rem 1rem;background:var(--steel-dark);color:var(--parchment);border-bottom:4px solid var(--orange)}.forge-shell a{color:inherit;text-decoration:none}.forge-mark{display:flex;align-items:center;gap:.6rem;font-family:var(--font-display);font-size:1.45rem;text-transform:uppercase}.forge-mark>span{padding:.3rem;background:var(--orange);color:#fff}.forge-shell nav{display:flex;justify-content:center;gap:1.2rem;font:700 .68rem var(--font-body);text-transform:uppercase}.forge-account{font:700 .68rem var(--font-body);text-transform:uppercase}.forge-footer{display:flex;justify-content:space-between;gap:1rem;padding:1.5rem;background:var(--steel);color:var(--parchment)}.forge-footer nav{display:flex;gap:1rem}@media(max-width:760px){.forge-shell{grid-template-columns:1fr auto}.forge-shell nav{grid-column:1/-1;justify-content:flex-start;overflow:auto}.forge-account{grid-row:1;grid-column:2}.forge-shell nav a{min-width:max-content}}`,
      ),
    },
    home: {
      signature: "exploded-tool image plate over live catalog drawings and a verified line-item job loadout",
      source: source(
        `<main class="forge-frame"><section class="forge-hero"><div class="forge-hero-copy forge-copy forge-motion" ${motionAttributes("reveal")}><span class="forge-label">Active catalog</span><h1>Build from<br>the drawing.</h1><p>Inspect merchant-listed fit, stock, and options before anything enters the loadout.</p><a data-cd-route="collections">Open project doorways</a></div><figure class="forge-hero-media"><img class="forge-hero-image" data-cd-asset="hero" alt="Pro-grade hand tools arranged as an exploded technical study"><figcaption>Exploded tool study / approved hero image</figcaption></figure></section><section class="forge-live"><header><span class="forge-label">Current inventory</span><h2>Tools on the sheet</h2><p>Images, descriptions, prices, and availability come directly from the merchant catalog.</p></header><div class="forge-grid" data-cd-repeat="featured.products">${productCard}</div><p data-cd-empty-state>No live tools are available for this drawing.</p></section><section class="forge-discovery"><header><span class="forge-label">Live project collections</span><h2>Choose the job shape.</h2><p>These paths use merchant collection records when supplied, then return to the full tool index when a project is empty.</p></header><div class="forge-project-grid" data-cd-repeat="featured.collections">${collectionCard}</div><a data-cd-route="collections">Open every project doorway</a></section><section class="forge-bundle forge-motion" ${motionAttributes("reveal")}><div class="forge-bundle-copy"><span class="forge-label">Job loadout</span><h2>Build a three-line project kit.</h2><p>Choose three real products. The protected builder verifies each current variant, price, and availability before it adds the complete kit.</p></div></section><section data-cd-repeat="featured.products"><div data-cd-key="product.id" data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline" data-cd-theme-tokens="steel steel-dark orange parchment"></div></section></main><section data-cd-slot="bundleBuilder" data-cd-bundle-slots="3" data-cd-host-size="block" data-cd-theme-tokens="steel steel-dark orange parchment"></section>`,
        `.forge-hero{display:grid;grid-template-columns:.86fr 1.14fr;min-height:680px;border-bottom:1px solid var(--steel)}.forge-hero-copy{display:flex;flex-direction:column;justify-content:center;padding:clamp(2rem,6vw,6rem)}.forge-hero h1{max-width:9ch;margin:.5rem 0;font:700 clamp(4rem,6vw,6rem)/.86 var(--font-display);letter-spacing:-.045em;text-transform:uppercase}.forge-hero-copy>a{align-self:flex-start;margin-top:1rem;padding:.8rem 1rem;background:var(--orange);color:#fff;text-decoration:none;text-transform:uppercase}.forge-hero-media{position:relative;margin:1rem;background:var(--steel-dark);overflow:hidden}.forge-hero-image{display:block;width:100%;height:100%;object-fit:cover}.forge-hero-media figcaption{position:absolute;right:1rem;bottom:1rem;padding:.5rem;background:var(--parchment);font:700 .6rem var(--font-body);text-transform:uppercase}.forge-live{padding:clamp(2rem,5vw,5rem)}.forge-live>header{display:grid;grid-template-columns:1fr 1.5fr 1fr;align-items:end;gap:1rem;margin-bottom:2rem}.forge-live h2,.forge-bundle h2{margin:0;font:700 clamp(3rem,6vw,7rem)/.84 var(--font-display);text-transform:uppercase}.forge-discovery{padding:clamp(2rem,5vw,5rem);background:var(--parchment)}.forge-discovery header{max-width:62rem;margin-bottom:1.5rem}.forge-discovery h2{margin:.4rem 0;font:700 clamp(3rem,6vw,7rem)/.84 var(--font-display);text-transform:uppercase}.forge-project-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--steel)}.forge-discovery>a{display:inline-block;margin-top:1rem;padding:.8rem 1rem;background:var(--steel);color:var(--parchment);text-decoration:none;text-transform:uppercase}.forge-bundle{padding:clamp(2rem,5vw,5rem);background:var(--steel);color:var(--parchment)}.forge-bundle-copy{max-width:58rem}${productCardsCss}@media(max-width:760px){.forge-hero,.forge-live>header,.forge-project-grid{grid-template-columns:1fr}.forge-hero{min-height:0}.forge-hero-media{min-height:52dvh}.forge-hero h1{font-size:4rem}.forge-live .forge-grid{display:flex;overflow-x:auto;scroll-snap-type:x mandatory}.forge-live .forge-card{flex:0 0 82vw;scroll-snap-align:start}}@media(prefers-reduced-motion:reduce){.forge-live .forge-grid{scroll-behavior:auto}}`,
      ),
    },
    collection: {
      signature: "sticky merchant-tag project filters beside live tool diagrams and quick-view purchase controls",
      source: source(
        `<main class="forge-frame forge-catalog"><header class="forge-catalog-head forge-copy"><nav class="forge-crumbs" aria-label="Collection hierarchy"><a data-cd-route="home">Home</a> / <a data-cd-route="collections">Projects</a> / <span data-cd-text="collection.title"></span></nav><span class="forge-label">Project index / merchant record</span><h1 data-cd-text="collection.title"></h1><p data-cd-text="collection.description"></p><b><span data-cd-text="collection.productCount"></span> live entries</b></header><nav class="forge-siblings" aria-label="Sibling project records"><a data-cd-route="collections">All projects</a><a data-cd-route="collection">All tools</a><a data-cd-route="search">Search records</a></nav><nav class="forge-filters" aria-label="Project filters"><span>Project filters / live catalog tags</span><small>Only live products carrying the selected catalog tag appear.</small><div class="forge-applied"><b>Applied drawing marks</b><span>Visible when live filters are active.</span></div><label>Compatibility record<input name="compatibility" type="search" placeholder="Merchant-listed model" data-cd-on="change" data-cd-action="collection.filter" data-cd-facet="fact-compatibility"></label><button value="framing" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Framing</button><button value="finish" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Finish</button><button value="electrical" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Electrical</button><button value="repair" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">Repair</button><button value="relevance" data-cd-on="click" data-cd-action="collection.sort">Drawing order</button><button value="price_asc" data-cd-on="click" data-cd-action="collection.sort">Price low</button><button value="price_desc" data-cd-on="click" data-cd-action="collection.sort">Price high</button></nav><div class="forge-grid" data-cd-repeat="collection.products">${productCard}</div><p class="forge-empty" data-cd-empty-state>No live products match these merchant records. Return to project doorways or clear a drawing mark.</p></main><section data-cd-repeat="collection.products"><div data-cd-key="product.id" data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline" data-cd-theme-tokens="steel steel-dark orange parchment"></div></section>`,
        `.forge-catalog{display:grid;grid-template-columns:18rem 1fr}.forge-catalog-head{grid-column:1/-1;padding:clamp(2rem,5vw,5rem);background:var(--steel);color:var(--parchment)}.forge-catalog-head h1{margin:.5rem 0;font:700 clamp(4rem,9vw,9rem)/.8 var(--font-display);text-transform:uppercase}.forge-siblings{grid-column:1/-1;display:flex;gap:1px;background:var(--steel)}.forge-siblings a{flex:1;padding:1rem;background:var(--parchment);color:inherit;text-decoration:none;text-transform:uppercase}.forge-crumbs a{color:inherit}.forge-applied{padding:.7rem;border:1px dashed var(--line)}.forge-filters{position:sticky;top:0;align-self:start;display:grid;gap:.5rem;padding:1rem;background:var(--steel-dark);color:var(--parchment)}.forge-filters span{font:700 .65rem var(--font-body);text-transform:uppercase}.forge-filters label{display:grid;gap:.35rem;font-size:.65rem;text-transform:uppercase}.forge-filters button,.forge-filters input{min-width:0;padding:.8rem;border:1px solid var(--line);background:transparent;color:inherit;text-align:left}.forge-catalog>.forge-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.forge-empty{padding:2rem}${productCardsCss}@media(max-width:920px){.forge-catalog{grid-template-columns:1fr}.forge-filters{position:static;grid-template-columns:repeat(2,1fr)}.forge-catalog>.forge-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.forge-catalog>.forge-grid{grid-template-columns:1fr}}`,
      ),
    },
    product: {
      signature: "exploded live product gallery paired with merchant compatibility record and protected controls",
      source: source(
        `<main class="forge-frame forge-product"><section class="forge-product-media"><div class="forge-drawings" data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="920" height="920"></figure></div></section><article class="forge-spec forge-copy"><span class="forge-label">Merchant compatibility record</span><h1 data-cd-text="product.title"></h1><p data-cd-text="product.description"></p><div class="forge-price"><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span></div><section><h2>Declared facts</h2><div class="forge-facts" data-cd-repeat="product.facts"><article data-cd-key="fact.id"><b data-cd-text="fact.label"></b><span data-cd-text="fact.value"></span><a data-cd-href="fact.url">Open merchant reference</a></article></div><p data-cd-empty-state>No compatibility, dimension, material, or reference facts were supplied for this product.</p></section><section><h2>Declared options</h2><p>Only options and availability supplied by this merchant appear below. Confirm the selected line before purchase.</p><div data-cd-repeat="product.variants"><div class="forge-variant" data-cd-key="variant.id"><b data-cd-text="variant.title"></b><span data-cd-money="variant.price"></span><small data-cd-text="variant.availability"></small></div></div></section><aside class="forge-policy"><h2>Policy check before loadout</h2><p>Review the merchant policy links before adding a selected variant to the loadout.</p><nav data-cd-policy-links></nav></aside><section><h2>Related project records</h2><div class="forge-grid" data-cd-repeat="related.products">${productCard}</div></section></article></main><div data-cd-slot="variantPicker" data-cd-host-size="block" data-cd-theme-tokens="steel steel-dark orange parchment"></div><div data-cd-slot="addToCart" data-cd-host-size="block" data-cd-theme-tokens="steel steel-dark orange parchment"></div>`,
        `.forge-product{display:grid;grid-template-columns:1.15fr .85fr;min-height:80dvh}.forge-product-media{padding:1rem;border-right:1px solid var(--steel);background:linear-gradient(135deg,var(--steel-dark),var(--steel))}.forge-drawings{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:var(--line)}.forge-drawings figure{margin:0;background:var(--parchment)}.forge-drawings img{display:block;width:100%;aspect-ratio:1;object-fit:cover}.forge-spec{position:sticky;top:0;align-self:start;padding:clamp(2rem,5vw,5rem)}.forge-spec h1{margin:.5rem 0;font:700 clamp(4rem,7vw,8rem)/.8 var(--font-display);text-transform:uppercase}.forge-price{display:flex;justify-content:space-between;padding:1rem 0;border-block:1px solid var(--steel);font-size:1.1rem}.forge-spec h2{font-family:var(--font-display);text-transform:uppercase}.forge-facts article,.forge-variant{display:grid;grid-template-columns:1fr auto;gap:.35rem;padding:.7rem 0;border-bottom:1px solid var(--line)}.forge-facts a{grid-column:1/-1;color:var(--orange);font-size:.72rem}.forge-policy{margin-top:1rem;padding:1rem;border:1px solid var(--steel)}.forge-variant small{grid-column:1/-1}@media(max-width:860px){.forge-product{grid-template-columns:1fr}.forge-product-media{border-right:0}.forge-spec{position:static}}`,
        "product",
      ),
    },
    search: {
      signature: "overscale drawing query with live merchant matches and explicit empty-plan state",
      source: source(
        `<main class="forge-frame forge-search"><header class="forge-search-head forge-copy"><span class="forge-label">Drawing query / live catalog</span><h1 data-cd-text="search.query">Find the right line.</h1><div><input aria-label="Search live catalog" type="search" name="q" placeholder="Tool, project tag, or merchant-listed detail" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Run query</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear</button></div><b>Matching live records</b><a data-cd-route="collections">Open project doorways</a></header><div class="forge-grid" data-cd-repeat="search.results">${productCard}</div><p class="forge-empty" data-cd-empty-state>No live catalog lines match this query. Open project doorways to recover by category.</p></main>`,
        `.forge-search-head{padding:clamp(2rem,7vw,7rem);background:var(--steel);color:var(--parchment)}.forge-search-head h1{margin:.5rem 0;font:700 clamp(4rem,10vw,11rem)/.78 var(--font-display);text-transform:uppercase}.forge-search-head input,.forge-search-head button{padding:1rem;border:1px solid var(--parchment);background:transparent;color:inherit}.forge-search-head input{width:min(35rem,100%)}.forge-empty{padding:2rem}${productCardsCss}`,
        "search",
      ),
    },
    cart: {
      signature: "construction loadout ledger with live line controls and trusted order summary",
      source: source(
        `<main class="forge-frame forge-cart"><header class="forge-cart-head"><span class="forge-label">Loadout / current cart</span><h1>Every line accounted for.</h1><b><span data-cd-text="cart.count"></span> items</b></header><section class="forge-lines" data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><div><h2 data-cd-text="cartLine.title"></h2><span>Quantity <b data-cd-text="cartLine.quantity"></b></span></div><span data-cd-money="cartLine.unitPrice"></span><strong data-cd-money="cartLine.total"></strong></article></section><aside class="forge-progress"><span>Review lines</span><span>Confirm protected checkout</span><span>Policy links</span></aside><aside class="forge-total"><span>Subtotal</span><b data-cd-money="cart.subtotal"></b><span>Total</span><strong data-cd-money="cart.total"></strong></aside><p class="forge-policy-note">Merchant policy links remain available before checkout.</p><nav class="forge-cart-policies" data-cd-policy-links></nav><div class="forge-empty" data-cd-empty-state><p>The loadout is empty.</p><a data-cd-route="collections">Open project doorways</a></div></main><section data-cd-repeat="cart.lines"><div data-cd-key="cartLine.id" data-cd-slot="cartLineControls" data-cd-host-size="inline"></div></section><div data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="steel steel-dark orange parchment"></div>`,
        `.forge-cart-head{padding:clamp(2rem,6vw,6rem);background:var(--orange);color:#fff}.forge-cart-head h1{max-width:11ch;margin:.5rem 0;font:700 clamp(4rem,9vw,9rem)/.8 var(--font-display);text-transform:uppercase}.forge-lines{padding:1rem}.forge-lines article{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:1rem;padding:1rem;border-bottom:1px solid var(--steel)}.forge-progress{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;padding:1rem;background:var(--steel)}.forge-progress span{padding:1rem;background:var(--parchment);text-transform:uppercase}.forge-policy-note,.forge-cart-policies{padding:1rem 2rem}.forge-total{display:grid;grid-template-columns:1fr auto;gap:1rem;width:min(34rem,100%);margin-left:auto;padding:2rem;background:var(--steel);color:var(--parchment)}.forge-empty{padding:2rem}@media(max-width:760px){.forge-lines article{grid-template-columns:1fr auto}}`,
        "cart",
      ),
    },
    checkout: {
      signature: "parchment drawing-title checkout with compact protected-flow trust rail",
      source: {
        html: `<header class="forge-checkout"><span>Final drawing / secure checkout</span><h1 data-cd-text="store.name">Forge</h1><p>Confirm contact, delivery, consent, and payment in the protected checkout flow.</p></header><section class="forge-checkout-rail"><b>Live order summary</b><span>Merchant policies remain available below.</span></section><footer data-cd-policy-links></footer>`,
        css: `.forge-checkout{padding:48px;background-color:var(--parchment);color:var(--ink)}.forge-checkout h1{font-family:var(--font-display);font-size:72px;font-weight:700;line-height:.8}.forge-checkout-rail{display:grid;gap:8px;padding:32px;background-color:var(--steel);color:var(--parchment)}`,
        layout: {
          columnMode: "summaryAside",
          sectionOrder: ["contact", "shipping", "delivery", "consent", "payment", "summary"],
          spacingTokenId: "drawing-gap",
          surfaceTokenIds: ["parchment", "steel", "orange"],
        },
      },
    },
    collections: {
      signature: "project-doorway index that routes to live tagged inventory without asserting hidden bundles",
      source: source(
        `<main class="forge-frame forge-projects"><header><span class="forge-label">Project doorways / catalog navigation</span><h1>Start with the job.</h1><p>Merchant collection records form the first layer. The live tool index remains available when a project has no assigned products.</p><a data-cd-route="collection">Open all tools</a></header><section class="forge-project-grid" data-cd-repeat="featured.collections">${collectionCard}</section><p class="forge-empty" data-cd-empty-state>No merchant collections are available yet. Open the full tool index to browse current products.</p><section class="forge-grid" data-cd-repeat="featured.products">${productCard}</section></main>`,
        `.forge-projects>header{padding:clamp(2rem,6vw,6rem);background:var(--steel);color:var(--parchment)}.forge-projects h1{margin:.5rem 0;font:700 clamp(4rem,10vw,11rem)/.78 var(--font-display);text-transform:uppercase}.forge-projects>header a{display:inline-block;margin-top:1rem;padding:.8rem 1rem;background:var(--orange);color:#fff;text-decoration:none;text-transform:uppercase}.forge-projects .forge-project-grid{grid-template-columns:repeat(2,1fr)}${productCardsCss}@media(max-width:700px){.forge-projects>nav{grid-template-columns:1fr}}`,
      ),
    },
    story: {
      signature: "field-note chronology pairing optional jobsite footage with merchant catalog evidence rules",
      source: source(
        `<main class="forge-frame forge-story"><section class="forge-story-hero"><div><span class="forge-label">Field notes / evidence rule</span><h1>Read the mark.<br>Check the record.</h1><p>Forge presents only the images, options, compatibility language, prices, and availability supplied by the merchant.</p><a data-cd-route="collection">Inspect live records</a></div><figure role="img" aria-label="Abstract technical drawing grid"><figcaption>Jobsite context / drawing study</figcaption></figure></section><section class="forge-notes"><article><h2>Observe</h2><p>Use live product imagery and descriptions as the source of truth.</p></article><article><h2>Compare</h2><p>Compare merchant-declared options without adding performance standards.</p></article><article><h2>Confirm</h2><p>Select the current variant and use protected commerce controls.</p></article></section></main>`,
        `.forge-story-hero{display:grid;grid-template-columns:1fr 1fr;min-height:72dvh}.forge-story-hero>div{display:flex;flex-direction:column;justify-content:center;padding:clamp(2rem,6vw,6rem);background:var(--steel);color:var(--parchment)}.forge-story h1{margin:.6rem 0;font:700 clamp(4rem,8vw,9rem)/.8 var(--font-display);text-transform:uppercase}.forge-story a{align-self:flex-start;padding:.8rem 1rem;background:var(--orange);color:#fff;text-decoration:none}.forge-story figure{position:relative;margin:0;background:linear-gradient(90deg,transparent 95%,var(--line) 95%),linear-gradient(0deg,transparent 95%,var(--line) 95%),var(--steel-dark);background-size:3rem 3rem}.forge-story figure figcaption{position:absolute;right:1rem;bottom:1rem;padding:.5rem;background:var(--parchment);font-size:.65rem}.forge-notes{display:grid;grid-template-columns:repeat(3,1fr)}.forge-notes article{padding:clamp(2rem,4vw,4rem);border:1px solid var(--steel)}.forge-notes b{color:var(--orange)}.forge-notes h2{font:700 3rem var(--font-display);text-transform:uppercase}@media(max-width:760px){.forge-story-hero,.forge-notes{grid-template-columns:1fr}.forge-story figure{min-height:50dvh}}`,
      ),
    },
    notFound: {
      signature: "misread-coordinate recovery plate routing back to projects, tools, and search",
      source: source(
        `<main class="forge-frame forge-missing"><span class="forge-label">Drawing not found / 404</span><h1>Wrong coordinate.</h1><p>This route is not on the current plan.</p><nav><a data-cd-route="collections">Open projects</a><a data-cd-route="collection">Open tools</a><a data-cd-route="search">Search the catalog</a></nav></main>`,
        `.forge-missing{display:grid;place-content:center;min-height:75dvh;padding:2rem;text-align:center}.forge-missing h1{margin:.5rem 0;font:700 clamp(5rem,14vw,14rem)/.75 var(--font-display);text-transform:uppercase}.forge-missing nav{display:flex;justify-content:center;gap:.5rem;flex-wrap:wrap}.forge-missing a{padding:.8rem 1rem;background:var(--steel);color:var(--parchment);text-decoration:none}`,
      ),
    },
  },
  assets: FORGE_ASSETS,
} satisfies RecipeConfig<"forge">;

export const FORGE_RECIPE = compileRecipeConfig(FORGE_RECIPE_CONFIG);
export const FORGE_BUNDLE = FORGE_RECIPE.bundle;
