import { defineRecipe, type RecipeConfig } from "../factory";
import { BROADCAST_PATCH_BAY_ASSETS } from "./assets";

const config = {
  templateId: "broadcast-patch-bay", templateVersion: 1,
  concept: { name: "Broadcast Patch Bay", rationale: "A modular creator storefront that routes the catalog as an input-to-output signal chain.", noveltySignature: ["signal-patch-bay", "rig-mode-routing", "compatibility-modules"] },
  designSystem: {
    displayFontId: "space-grotesk", bodyFontId: "ibm-plex-mono",
    tokens: { black: "#0b0d12", panel: "#151923", panel2: "#202634", white: "#eff3f8", muted: "#8993a3", blue: "#2d6bff", amber: "#ffb31a", signal: "#4df3b5", red: "#ff5362", "rack-gap": "18px" },
    breakpoints: { compact: 850, wide: 1300 }, iconStyle: "signal-path glyphs and compatibility-port marks", motionStyle: "modular patch transitions with reduced-motion static routing",
    globalCss: `.broadcast-title{font-family:var(--font-display);font-weight:700;letter-spacing:-.06em;line-height:.84;text-transform:uppercase}.channel-label{font-family:var(--font-body);font-size:.64rem;letter-spacing:.16em;text-transform:uppercase;color:var(--signal)}`,
  },
  archetype: { composition: "signal-patch-bay", hero: "rig-signal-chain", scroll: "modular-patching", cards: "signal-modules", iconography: ["signal path glyphs", "compatibility port marks"] },
  surfaces: {
    shell: { signature: "on-air status rail above rig-mode navigation and active-loadout commerce bay", source: {
      html: `<header class="patch-shell"><span class="niche-icon niche-icon--broadcast" aria-hidden="true">&#8984;</span><span class="channel-label">On air / signal stable</span><a class="broadcast-title" data-cd-route="home" data-cd-text="store.name">Patch Bay</a><nav aria-label="Broadcast navigation"><a data-cd-route="collection">Catalog</a><a data-cd-route="search">Query</a><a data-cd-route="account">Account</a><a data-cd-route="cart">Loadout <span data-cd-text="cart.count"></span></a></nav></header><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="black panel blue signal"></aside><footer data-cd-policy-links></footer>`,
      css: `.patch-shell nav{display:flex;gap:.5rem}.patch-shell nav a{padding:.65rem;border:1px solid var(--panel2);color:var(--white)}.broadcast-title{font-size:1.6rem;color:var(--white)}`, requiredData: [], requiredCapabilities: [],
    } },
    home: { signature: "split signal-chain hero followed by linked channel modules and reconfigurable creator rack", source: {
      html: `<main><section class="signal-hero"><div class="signal-copy resilient-copy"><small class="channel-label">Channel 01 / Play</small><h1 class="broadcast-title">Build the clean signal.</h1><p>Route control, audio, image, light, and output as one compatible system.</p><a data-cd-route="collection">Route the catalog</a></div><figure class="signal-image"><img data-cd-asset="hero" alt="Creator broadcast desk arranged as a complete signal chain" width="1600" height="1200"></figure></section><section class="patch-section"><nav class="rig-modes" aria-label="Rig mode"><button value="play" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="rig-stage">Play</button><button value="stream" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="rig-stage">Stream</button><button value="record" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="rig-stage">Record</button><button value="publish" data-cd-on="click" data-cd-action="tabs.select" data-cd-target="rig-stage">Publish</button></nav><article id="rig-stage" class="rig-stage resilient-copy"><small class="channel-label">Live routing</small><h2 class="broadcast-title">Your signal chain</h2><p>Start at the input. Inspect each compatible module before it reaches the active loadout.</p></article></section><section data-cd-repeat="featured.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="620" height="620"><h2 data-cd-text="product.title"></h2><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Open module</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="chain-empty resilient-copy">No compatible signal found. Switch rig mode or open every channel.</p></main>`,
      css: `.signal-hero{display:grid;grid-template-columns:.9fr 1.1fr;min-height:74dvh;background:var(--black);color:var(--white)}.signal-copy{align-self:center;padding:clamp(2rem,6vw,6rem)}.signal-copy h1{font-size:clamp(4rem,9vw,9rem);max-width:7ch}.signal-image{margin:1rem;border:1px solid var(--panel2)}.signal-image img{display:block;width:100%;height:70dvh;object-fit:cover;filter:saturate(.8) contrast(1.1)}.patch-section{display:grid;grid-template-columns:.55fr 1.45fr;gap:2rem;padding:clamp(2rem,6vw,6rem);background:var(--panel);color:var(--white)}.rig-modes{display:grid;gap:.5rem}.rig-modes button{padding:1rem;border:1px solid var(--panel2);background:var(--black);color:var(--white)}.rig-stage h2{font-size:clamp(3rem,7vw,7rem)}.rig-stage[data-cd-active-value]{border-left:5px solid var(--signal);padding-left:1.25rem}.signal-copy,.rig-stage,.chain-empty,.resilient-copy{overflow-wrap:anywhere}.chain-empty{padding:2rem;background:var(--black);color:var(--muted)}@media(max-width:850px){.signal-hero,.patch-section{grid-template-columns:1fr}.signal-image img{height:50dvh}}@media(prefers-reduced-motion:reduce){.signal-image img{filter:none}}`, requiredData: [], requiredCapabilities: [],
    } },
    collection: { signature: "dark channel matrix with compatibility facets and live module-routing inventory", source: {
      html: `<main><header class="channel-head resilient-copy"><small class="channel-label">Catalog matrix</small><h1 class="broadcast-title" data-cd-text="collection.title"></h1><p data-cd-text="collection.description"></p><b data-cd-text="collection.productCount"></b></header><nav class="channel-filters"><button value="control" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="category">Control</button><button value="audio" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="category">Audio</button><button value="capture" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="category">Capture</button><button value="usb-c" data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="tag">USB-C</button><button value="relevance" data-cd-on="click" data-cd-action="collection.sort">Signal order</button></nav><section data-cd-repeat="collection.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="620" height="620"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Inspect module</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="module-empty resilient-copy">No compatible signal found. Clear a role or port filter.</p><p class="sold-module">Sold out modules remain visible for Compatibility planning.</p></main>`,
      css: `.channel-head{padding:clamp(2rem,6vw,6rem);background:var(--panel);color:var(--white)}.channel-head h1{font-size:clamp(4rem,9vw,9rem)}.channel-filters{position:sticky;top:0;display:flex;gap:.4rem;padding:1rem;background:var(--black);overflow:auto}.channel-filters button{padding:.75rem;border:1px solid var(--panel2);background:var(--panel);color:var(--white)}.channel-head,.module-empty,.resilient-copy{overflow-wrap:anywhere}.module-empty,.sold-module{padding:1.5rem;background:var(--black);color:var(--muted)}`, requiredData: [], requiredCapabilities: [],
    } },
    product: { signature: "four-quadrant module gallery paired with compatibility passport and patch-in purchase ports", source: {
      html: `<main><section class="module-gallery" data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="920" height="920"></figure></section><header class="module-passport resilient-copy"><small class="channel-label">Module passport</small><h1 class="broadcast-title" data-cd-text="product.title"></h1><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><h2>Compatibility</h2><p>Confirm the live variant, port, and signal role before patching this module into a loadout.</p><p>Sold out configurations remain documented for chain planning.</p></header><section data-cd-repeat="product.variants"><div data-cd-key="variant.id"><b data-cd-text="variant.title"></b><span data-cd-text="variant.availability"></span><strong data-cd-money="variant.price"></strong></div></section><div data-cd-slot="variantPicker" data-cd-host-size="block" data-cd-theme-tokens="black panel blue signal"></div><div data-cd-slot="addToCart" data-cd-host-size="block" data-cd-theme-tokens="black panel blue signal"></div></main>`,
      css: `.module-gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:2px;background:var(--black)}.module-gallery figure{margin:0}.module-gallery img{display:block;width:100%;height:64dvh;object-fit:cover}.module-passport{padding:clamp(2rem,5vw,5rem);max-width:70rem;background:var(--panel);color:var(--white)}.module-passport h1{font-size:clamp(4rem,8vw,8rem)}.module-passport,.resilient-copy{overflow-wrap:anywhere}@media(max-width:850px){.module-gallery{grid-template-columns:1fr}.module-gallery img{height:48dvh}}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "product",
    } },
    search: { signature: "console-scale signal query feeding ranked compatibility modules and fault-state message", source: {
      html: `<main><header class="signal-query resilient-copy"><small class="channel-label">Search role / platform / specification</small><h1 class="broadcast-title" data-cd-text="search.query">Query the patch bay</h1><input aria-label="Query the patch bay" type="search" name="q" value="" placeholder="Role, platform, port, or specification" data-cd-on="input" data-cd-action="search.update"><button value="submit" data-cd-on="click" data-cd-action="search.submit">Route query</button><button value="clear" data-cd-on="click" data-cd-action="search.clear">Clear signal</button></header><section data-cd-repeat="search.results"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><a data-cd-route="product" data-cd-param-handle="product.handle">Open match</a></article></section><p class="query-fault resilient-copy">No compatible signal found. Query a role, platform, port, or specification.</p></main>`,
      css: `.signal-query{padding:clamp(2rem,7vw,7rem);background:var(--black);color:var(--white)}.signal-query h1{font-size:clamp(4rem,9vw,9rem);color:var(--signal)}.signal-query input,.signal-query button{padding:.8rem;margin-right:.5rem;background:var(--blue);color:var(--white);border:0}.signal-query,.query-fault,.resilient-copy{overflow-wrap:anywhere}.query-fault{padding:2rem;background:var(--panel);color:var(--muted)}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "search",
    } },
    cart: { signature: "active-loadout rack ledger with module quantities and summary-first signal total", source: {
      html: `<main><header class="loadout-head resilient-copy"><small class="channel-label">Active loadout</small><h1 class="broadcast-title">Order routing</h1><span data-cd-text="cart.count"></span></header><section data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><span data-cd-text="cartLine.quantity"></span><b data-cd-money="cartLine.unitPrice"></b><strong data-cd-money="cartLine.total"></strong><div data-cd-slot="cartLineControls" data-cd-host-size="inline"></div></article></section><aside class="loadout-total resilient-copy"><span>Subtotal</span><b data-cd-money="cart.subtotal"></b><span>Total</span><strong data-cd-money="cart.total"></strong></aside><div data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="black panel blue signal"></div><p class="loadout-empty resilient-copy">No modules patched yet. Begin at any signal-chain role.</p></main>`,
      css: `.loadout-head{padding:clamp(2rem,6vw,6rem);background:var(--blue);color:var(--white)}.loadout-head h1{font-size:clamp(4rem,9vw,9rem)}.loadout-total{display:grid;grid-template-columns:1fr auto;gap:1rem;padding:2rem;max-width:40rem;margin-left:auto;background:var(--panel);color:var(--white)}.loadout-head,.loadout-total,.loadout-empty,.resilient-copy{overflow-wrap:anywhere}.loadout-empty{padding:2rem;background:var(--black);color:var(--muted)}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "cart",
    } },
    checkout: { signature: "summary-first broadcast checkout with route confirmation and compatibility trust channel", source: {
      html: `<header class="checkout-channel"><small>Checkout channel</small><h1 data-cd-text="store.name">Broadcast Patch Bay</h1><p>Review the active loadout before contact, delivery, consent, and secure payment.</p></header><aside class="route-trust"><b>Compatibility retained</b><span>Tracked creator dispatch</span><span>Encrypted payment</span></aside><footer data-cd-policy-links></footer>`,
      css: `.checkout-channel{padding:46px;max-width:780px}.checkout-channel h1{font-size:68px}.route-trust{display:grid;gap:10px;padding:30px;background-color:var(--panel);color:var(--white)}`,
      layout: { columnMode: "summaryFirst", sectionOrder: ["summary", "contact", "shipping", "delivery", "consent", "payment"], spacingTokenId: "rack-gap", surfaceTokenIds: ["black", "panel", "blue", "signal"] },
    } },
  }, assets: BROADCAST_PATCH_BAY_ASSETS,
} satisfies RecipeConfig<"broadcast-patch-bay">;

export const BROADCAST_PATCH_BAY_RECIPE = defineRecipe(config);
export const BROADCAST_PATCH_BAY_BUNDLE = BROADCAST_PATCH_BAY_RECIPE.bundle;
