import { defineRecipe, type RecipeConfig } from "../factory";
import { REP_REST_ASSETS } from "./assets";

const config = {
  templateId: "rep-rest", templateVersion: 1,
  concept: { name: "Rep / Rest", rationale: "A high-contrast split journey that treats training and recovery as equal halves of one system.", noveltySignature: ["training-recovery-split", "sticky-workout-chapters", "comparison-rails"] },
  designSystem: {
    displayFontId: "archivo-narrow", bodyFontId: "inter",
    tokens: { ink: "#131611", acid: "#d7ff43", cream: "#f2f0e8", orange: "#ff5d34", line: "#777970", interval: "24px" },
    breakpoints: { compact: 800, wide: 1240 }, iconStyle: "interval arrows and recovery-state glyphs", motionStyle: "sticky workout chapters with kinetic split transitions",
    globalCss: `.performance-title{font-family:var(--font-display);font-weight:700;letter-spacing:-.055em;line-height:.82;text-transform:uppercase}.interval-mark{font-family:var(--font-body);font-weight:700;letter-spacing:.14em;text-transform:uppercase}`,
  },
  archetype: { composition: "split-performance", hero: "training-recovery-split", scroll: "sticky-workout", cards: "comparison-rails", iconography: ["training interval marks", "recovery status glyphs"] },
  surfaces: {
    shell: { signature: "sticky performance bar with train-recover axis and compact bag control", source: {
      html: `<header class="performance-bar"><a class="performance-title" data-cd-route="home" data-cd-text="store.name">Rep / Rest</a><nav aria-label="Training navigation"><a data-cd-route="collection">Train</a><a data-cd-route="collection">Recover</a><a data-cd-route="search">Search</a><a data-cd-route="cart">Work set</a></nav></header><aside data-cd-slot="cartDrawer" data-cd-host-size="panel" data-cd-theme-tokens="cream ink acid"></aside>`,
      css: `.performance-bar nav{display:flex;gap:1rem}.performance-bar nav a{font-size:.72rem;font-weight:700;text-transform:uppercase}.performance-title{font-size:1.7rem}`, requiredData: [], requiredCapabilities: [],
    } },
    home: { signature: "diagonal two-state hero followed by horizontal movement lanes and sticky recovery chapter", source: {
      html: `<main><section class="split-hero"><div class="training-copy resilient-copy"><small class="interval-mark">Training</small><h1 class="performance-title">Earn the rest.</h1><p>Technical layers and compact tools for the work between starting and stopping.</p><a data-cd-route="collection">Enter the work set</a></div><figure class="training-image"><img data-cd-asset="hero" alt="Athlete moving through an outdoor training interval" width="1600" height="1200"></figure><div class="recovery-copy resilient-copy"><small class="interval-mark">Recovery</small><p>Downshift with mobility tools, soft layers, and equipment sized for real rooms.</p></div></section><nav class="state-toggle"><button data-cd-on="click" data-cd-action="scroll.to" data-cd-target="work">Training</button><button data-cd-on="click" data-cd-action="scroll.to" data-cd-target="recover">Recovery</button></nav><section id="work" class="work-chapter"><h2 class="performance-title">Work set</h2><p class="resilient-copy">Current merchant stock, variants, and movement notes.</p></section><section data-cd-repeat="featured.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="640" height="760"><h3 data-cd-text="product.title"></h3><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Inspect movement</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><section id="recover" class="recovery-chapter"><h2 class="performance-title">Rest is part of the set.</h2><p class="resilient-copy">Recovery is a training state, not an afterthought.</p></section><p class="home-empty resilient-copy">No gear matches this training state. Switch lanes to continue.</p></main>`,
      css: `.split-hero{display:grid;grid-template-columns:.85fr 1.15fr;min-height:76dvh;background:var(--ink);color:var(--cream)}.training-copy{align-self:center;padding:clamp(2rem,6vw,6rem)}.training-copy h1{font-size:clamp(5rem,11vw,11rem);max-width:6ch;color:var(--acid)}.training-image{margin:0}.training-image img{display:block;width:100%;height:76dvh;object-fit:cover}.recovery-copy{padding:2rem;background:var(--orange)}.state-toggle{display:flex;background:var(--acid)}.state-toggle button{flex:1;padding:1rem;border:0;background:transparent;font-weight:800}.work-chapter,.recovery-chapter{min-height:52dvh;padding:clamp(2rem,8vw,8rem)}.work-chapter h2,.recovery-chapter h2{font-size:clamp(4rem,9vw,9rem)}.home-empty,.resilient-copy{overflow-wrap:anywhere}.home-empty{padding:2rem}@media(max-width:800px){.split-hero{grid-template-columns:1fr}.training-image img{height:48dvh}}`, requiredData: [], requiredCapabilities: [],
    } },
    collection: { signature: "lane-filtered equipment matrix with comparison view switch and persistent interval controls", source: {
      html: `<main><header class="inventory-head resilient-copy"><small class="interval-mark">Training inventory</small><h1 class="performance-title" data-cd-text="collection.title"></h1><p data-cd-text="collection.description"></p><b data-cd-text="collection.productCount"></b></header><nav class="lane-filters"><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="state">Apparel</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="state">Equipment</button><button data-cd-on="click" data-cd-action="collection.filter" data-cd-facet="state">Recovery</button><button data-cd-on="click" data-cd-action="collection.sort">Performance order</button><button data-cd-on="click" data-cd-action="collection.view">Comparison rail</button></nav><section data-cd-repeat="collection.products"><article data-cd-key="product.id"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="620" height="760"><h2 data-cd-text="product.title"></h2><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><a data-cd-route="product" data-cd-param-handle="product.handle">Open movement notes</a><div data-cd-slot="quickViewCommerce" data-cd-product="product.id" data-cd-host-size="inline"></div></article></section><p class="inventory-empty resilient-copy">No gear matches this training state. Clear a lane filter.</p><p class="sold-note">Sold out sizes remain listed for comparison.</p></main>`,
      css: `.inventory-head{padding:clamp(2rem,6vw,6rem);background:var(--cream)}.inventory-head h1{font-size:clamp(4rem,10vw,10rem)}.lane-filters{position:sticky;top:0;display:flex;gap:.5rem;padding:1rem;background:var(--acid);overflow:auto}.lane-filters button{padding:.75rem;border:1px solid var(--ink);background:transparent;font-weight:800}.inventory-empty,.resilient-copy{overflow-wrap:anywhere}.inventory-empty,.sold-note{padding:1.5rem}`, requiredData: [], requiredCapabilities: [],
    } },
    product: { signature: "full-height movement image pair with condensed performance dossier and recovery-aware purchase stack", source: {
      html: `<main><section class="motion-gallery" data-cd-repeat="product.images"><figure data-cd-key="product.primaryImage"><img data-cd-src="product.primaryImage" data-cd-alt="product.title" width="960" height="1100"></figure></section><header class="movement-dossier resilient-copy"><small class="interval-mark">Movement tested</small><h1 class="performance-title" data-cd-text="product.title"></h1><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><span data-cd-text="product.availability"></span><p>Sold out variants stay in the range so sizing and training notes remain clear.</p></header><section data-cd-repeat="product.variants"><div data-cd-key="variant.id"><b data-cd-text="variant.title"></b><span data-cd-text="variant.availability"></span><strong data-cd-money="variant.price"></strong></div></section><div data-cd-slot="variantPicker" data-cd-host-size="block" data-cd-theme-tokens="cream ink acid"></div><div data-cd-slot="addToCart" data-cd-host-size="block" data-cd-theme-tokens="cream ink acid"></div></main>`,
      css: `.motion-gallery{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--ink)}.motion-gallery figure{margin:0}.motion-gallery img{display:block;width:100%;height:70dvh;object-fit:cover}.movement-dossier{padding:clamp(2rem,6vw,6rem);max-width:64rem}.movement-dossier h1{font-size:clamp(4rem,9vw,9rem)}.movement-dossier,.resilient-copy{overflow-wrap:anywhere}@media(max-width:800px){.motion-gallery{grid-template-columns:1fr}.motion-gallery img{height:52dvh}}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "product",
    } },
    search: { signature: "oversized movement query header above horizontally ranked training-result lane", source: {
      html: `<main><header class="movement-query resilient-copy"><small class="interval-mark">Find a movement system</small><h1 class="performance-title" data-cd-text="search.query">Search gear</h1><button data-cd-on="click" data-cd-action="search.submit">Run search</button><button data-cd-on="click" data-cd-action="search.clear">Clear</button></header><section data-cd-repeat="search.results"><article data-cd-key="product.id"><h2 data-cd-text="product.title"></h2><p data-cd-text="product.description"></p><b data-cd-money="product.price"></b><a data-cd-route="product" data-cd-param-handle="product.handle">View result</a></article></section><p class="search-empty resilient-copy">No gear matches this training state. Try apparel, equipment, or recovery.</p></main>`,
      css: `.movement-query{padding:clamp(2rem,8vw,8rem);background:var(--ink);color:var(--cream)}.movement-query h1{font-size:clamp(4rem,11vw,11rem);color:var(--acid)}.movement-query button{padding:.8rem;margin-right:.5rem}.movement-query,.search-empty,.resilient-copy{overflow-wrap:anywhere}.search-empty{padding:2rem}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "search",
    } },
    cart: { signature: "work-set line ledger paired with bold interval subtotal and platform quantity stations", source: {
      html: `<main><header class="workset-head resilient-copy"><small class="interval-mark">Work set</small><h1 class="performance-title">Ready for the interval</h1><span data-cd-text="cart.count"></span></header><section data-cd-repeat="cart.lines"><article data-cd-key="cartLine.id"><h2 data-cd-text="cartLine.title"></h2><span data-cd-text="cartLine.quantity"></span><b data-cd-money="cartLine.unitPrice"></b><strong data-cd-money="cartLine.total"></strong><div data-cd-slot="cartLineControls" data-cd-host-size="inline"></div></article></section><aside class="workset-total resilient-copy"><span>Subtotal</span><b data-cd-money="cart.subtotal"></b><span>Total</span><strong data-cd-money="cart.total"></strong></aside><div data-cd-slot="cartSummary" data-cd-host-size="page" data-cd-theme-tokens="cream ink acid"></div><p class="workset-empty resilient-copy">Your work set is empty. Choose a training or recovery lane.</p></main>`,
      css: `.workset-head{padding:clamp(2rem,7vw,7rem);background:var(--acid)}.workset-head h1{font-size:clamp(4rem,9vw,9rem)}.workset-total{display:grid;grid-template-columns:1fr auto;gap:1rem;padding:2rem;max-width:38rem;margin-left:auto}.workset-head,.workset-total,.workset-empty,.resilient-copy{overflow-wrap:anywhere}.workset-empty{padding:2rem}`, requiredData: [], requiredCapabilities: [], rootScopeKind: "cart",
    } },
    checkout: { signature: "summary-first performance checkout with recovery-colored delivery and trust block", source: {
      html: `<header class="checkout-performance"><small>Final interval</small><h1 data-cd-text="store.name">Rep / Rest</h1><p>Review the work set first, then complete contact, delivery, consent, and payment.</p></header><aside class="checkout-trust"><b>30-day training trial</b><span>Tracked dispatch</span><span>Secure payment</span></aside><footer data-cd-policy-links></footer>`,
      css: `.checkout-performance{padding:48px;max-width:760px}.checkout-performance h1{font-size:72px}.checkout-trust{display:grid;gap:12px;padding:32px;background-color:var(--acid)}`,
      layout: { columnMode: "summaryFirst", sectionOrder: ["summary", "contact", "shipping", "delivery", "consent", "payment"], spacingTokenId: "interval", surfaceTokenIds: ["cream", "ink", "acid", "orange"] },
    } },
  }, assets: REP_REST_ASSETS,
} satisfies RecipeConfig<"rep-rest">;

export const REP_REST_RECIPE = defineRecipe(config);
export const REP_REST_BUNDLE = REP_REST_RECIPE.bundle;
